export default {
  England: [
    'City of London',
    'Camden',
    'Greenwich',
    'Lewisham',
    'Suffolk',
    'Hackney',
    'Tower Hamlets',
    'Bedford',
    'Norfolk',
    'Cambridgeshire',
    'Hammersmith and Fulham',
    'Islington',
    'Hertfordshire',
    'Kensington and Chelsea',
    'Hounslow',
    'Surrey',
    'Lambeth',
    'Wandsworth',
    'Westminster',
    'Southwark',
    'Merton',
    'Barking and Dagenham',
    'Barnet',
    'Bexley',
    'Brent',
    'Wokingham',
    'Bradford',
    'Harrow',
    'Ealing',
    'Bromley',
    'Croydon',
    'Haringey',
    'Enfield',
    'Havering',
    'Hillingdon',
    'Kingston upon Thames',
    'Newham',
    'Redbridge',
    'Richmond upon Thames',
    'Sutton',
    'Waltham Forest',
    'Birmingham',
    'Wirral',
    'Coventry',
    'Dudley',
    'Sandwell',
    'Solihull',
    'Walsall',
    'Wolverhampton',
    'Knowsley',
    'Liverpool',
    'St. Helens',
    'Sefton',
    'Telford and Wrekin',
    'Bolton',
    'Bury',
    'Manchester',
    'Oldham',
    'Rochdale',
    'Salford',
    'Stockport',
    'Trafford',
    'Tameside',
    'Wigan',
    'Barnsley',
    'Doncaster',
    'Rotherham',
    'Sheffield',
    'Calderdale',
    'Kirklees',
    'Leeds',
    'Wakefield',
    'Gateshead',
    'Newcastle upon Tyne',
    'North Tyneside',
    'South Tyneside',
    'Sunderland',
    'Bristol, City of',
    'Bath and North East Somerset',
    'South Gloucestershire',
    'North Somerset',
    'County Durham',
    'Central Bedfordshire',
    'Luton',
    'Reading',
    'Windsor and Maidenhead',
    'West Berkshire',
    'Slough',
    'Bracknell Forest',
    'Buckinghamshire',
    'Milton Keynes',
    'Peterborough',
    'Cheshire East',
    'Cheshire West and Chester',
    'Warrington',
    'Halton',
    'Redcar and Cleveland',
    'Stockton-on-Tees',
    'Middlesbrough',
    'Hartlepool',
    'Cornwall',
    'Cumbria',
    'North Yorkshire',
    'Derbyshire',
    'Derby',
    'Devon',
    'Plymouth',
    'Torbay',
    'Dorset',
    'Bournemouth, Christchurch and Poole',
    'Darlington',
    'Brighton and Hove',
    'East Sussex',
    'West Sussex',
    'Essex',
    'Southend-on-Sea',
    'Thurrock',
    'Gloucestershire',
    'Hampshire',
    'Southampton',
    'Portsmouth',
    'Herefordshire, County of',
    'Worcestershire',
    'Kingston upon Hull, City of',
    'East Riding of Yorkshire',
    'North East Lincolnshire',
    'North Lincolnshire',
    'Isle of Wight',
    'Kent',
    'Medway',
    'Lancashire',
    'Blackburn with Darwen',
    'Blackpool',
    'Leicestershire',
    'Leicester',
    'Rutland',
    'Lincolnshire',
    'York',
    'North Northamptonshire',
    'West Northamptonshire',
    'Northumberland',
    'Nottinghamshire',
    'Nottingham',
    'Oxfordshire',
    'Shropshire',
    'Somerset',
    'Staffordshire',
    'Stoke-on-Trent',
    'Warwickshire',
    'Swindon',
    'Wiltshire',
    'Vale of Glamorgan',
    'Isles Of Scilly',
  ],
  Scotland: [
    'Aberdeen City',
    'Aberdeenshire',
    'Angus',
    'Argyll & Bute',
    'Clackmannanshire',
    'Dumfries & Galloway',
    'Dundee City',
    'East Ayrshire',
    'East Dunbartonshire',
    'East Lothian',
    'East Renfrewshire',
    'Edinburgh City',
    'Falkirk',
    'Fife',
    'Glasgow City',
    'Grant aided',
    'Highland',
    'Inverclyde',
    'Midlothian',
    'Moray',
    'Na h-Eileanan Siar',
    'North Ayrshire',
    'North Lanarkshire',
    'Orkney Islands',
    'Perth & Kinross',
    'Renfrewshire',
    'Scottish Borders',
    'Shetland Islands',
    'South Ayrshire',
    'South Lanarkshire',
    'Stirling',
    'West Dunbartonshire',
    'West Lothian',
  ],
  Wales: [
    'Blaenau Gwent',
    'Bridgend',
    'Caerphilly',
    'Cardiff',
    'Carmarthenshire',
    'Ceredigion',
    'Conwy',
    'Denbighshire',
    'Flintshire',
    'Gwynedd',
    'Isle of Anglesey',
    'Merthyr Tydfil',
    'Monmouthshire',
    'Neath Port Talbot',
    'Newport',
    'Pembrokeshire',
    'Powys',
    'Rhondda Cynon Taf',
    'Swansea',
    'The Vale of Glamorgan',
    'Torfaen',
    'Wrexham',
  ],
}
