export default {
  England: [
    'Barking and Dagenham',
    'Barnet',
    'Barnsley',
    'Bath and North East Somerset',
    'Bedford',
    'Bexley',
    'Birmingham',
    'Blackburn with Darwen',
    'Blackpool',
    'Bolton',
    'Bournemouth, Christchurch and Poole',
    'Bracknell Forest',
    'Bradford',
    'Brent',
    'Brighton and Hove',
    'Bristol, City of',
    'Bromley',
    'Buckinghamshire',
    'Bury',
    'Calderdale',
    'Cambridgeshire',
    'Camden',
    'Central Bedfordshire',
    'Cheshire East',
    'Cheshire West and Chester',
    'City of London',
    'Cornwall',
    'County Durham',
    'Coventry',
    'Croydon',
    'Cumbria',
    'Darlington',
    'Derby',
    'Derbyshire',
    'Devon',
    'Doncaster',
    'Dorset',
    'Dudley',
    'Ealing',
    'East Riding of Yorkshire',
    'East Sussex',
    'Enfield',
    'Essex',
    'Gateshead',
    'Gloucestershire',
    'Greenwich',
    'Hackney',
    'Halton',
    'Hammersmith and Fulham',
    'Hampshire',
    'Haringey',
    'Harrow',
    'Hartlepool',
    'Havering',
    'Herefordshire, County of',
    'Hertfordshire',
    'Hillingdon',
    'Hounslow',
    'Isle of Wight',
    'Isles Of Scilly',
    'Islington',
    'Kensington and Chelsea',
    'Kent',
    'Kingston upon Hull, City of',
    'Kingston upon Thames',
    'Kirklees',
    'Knowsley',
    'Lambeth',
    'Lancashire',
    'Leeds',
    'Leicester',
    'Leicestershire',
    'Lewisham',
    'Lincolnshire',
    'Liverpool',
    'Luton',
    'Manchester',
    'Medway',
    'Merton',
    'Middlesbrough',
    'Milton Keynes',
    'Newcastle upon Tyne',
    'Newham',
    'Norfolk',
    'North East Lincolnshire',
    'North Lincolnshire',
    'North Northamptonshire',
    'North Somerset',
    'North Tyneside',
    'North Yorkshire',
    'Northumberland',
    'Nottingham',
    'Nottinghamshire',
    'Oldham',
    'Oxfordshire',
    'Peterborough',
    'Plymouth',
    'Portsmouth',
    'Reading',
    'Redbridge',
    'Redcar and Cleveland',
    'Richmond upon Thames',
    'Rochdale',
    'Rotherham',
    'Rutland',
    'Salford',
    'Sandwell',
    'Sefton',
    'Sheffield',
    'Shropshire',
    'Slough',
    'Solihull',
    'Somerset',
    'South Gloucestershire',
    'South Tyneside',
    'Southampton',
    'Southend-on-Sea',
    'Southwark',
    'St. Helens',
    'Staffordshire',
    'Stockport',
    'Stockton-on-Tees',
    'Stoke-on-Trent',
    'Suffolk',
    'Sunderland',
    'Surrey',
    'Sutton',
    'Swindon',
    'Tameside',
    'Telford and Wrekin',
    'Thurrock',
    'Torbay',
    'Tower Hamlets',
    'Trafford',
    'Vale of Glamorgan',
    'Wakefield',
    'Walsall',
    'Waltham Forest',
    'Wandsworth',
    'Warrington',
    'Warwickshire',
    'West Berkshire',
    'West Northamptonshire',
    'West Sussex',
    'Westminster',
    'Wigan',
    'Wiltshire',
    'Windsor and Maidenhead',
    'Wirral',
    'Wokingham',
    'Wolverhampton',
    'Worcestershire',
    'York',
  ],
  Scotland: [
    'Aberdeen City',
    'Aberdeenshire',
    'Angus',
    'Argyll & Bute',
    'Clackmannanshire',
    'Dumfries & Galloway',
    'Dundee City',
    'East Ayrshire',
    'East Dunbartonshire',
    'East Lothian',
    'East Renfrewshire',
    'Edinburgh City',
    'Falkirk',
    'Fife',
    'Glasgow City',
    'Grant aided',
    'Highland',
    'Inverclyde',
    'Midlothian',
    'Moray',
    'Na h-Eileanan Siar',
    'North Ayrshire',
    'North Lanarkshire',
    'Orkney Islands',
    'Perth & Kinross',
    'Renfrewshire',
    'Scottish Borders',
    'Shetland Islands',
    'South Ayrshire',
    'South Lanarkshire',
    'Stirling',
    'West Dunbartonshire',
    'West Lothian',
  ],
  Wales: [
    'Blaenau Gwent',
    'Bridgend',
    'Caerphilly',
    'Cardiff',
    'Carmarthenshire',
    'Ceredigion',
    'Conwy',
    'Denbighshire',
    'Flintshire',
    'Gwynedd',
    'Isle of Anglesey',
    'Merthyr Tydfil',
    'Monmouthshire',
    'Neath Port Talbot',
    'Newport',
    'Pembrokeshire',
    'Powys',
    'Rhondda Cynon Taf',
    'Swansea',
    'The Vale of Glamorgan',
    'Torfaen',
    'Wrexham',
  ],
}
