-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."organization_member_role" add column "_source" varchar
--  null;
