CREATE TEMP TABLE IF NOT EXISTS country_codes (
    country_name VARCHAR PRIMARY KEY,
    iso_code CHAR(8)
);

INSERT INTO country_codes (country_name, iso_code) VALUES
    ('England', '"GB-ENG"'),
    ('Northern Ireland', '"GB-NIR"'),
    ('Scotland', '"GB-SCT"'),
    ('Wales', '"GB-WLS"'),
    ('Albania', '"AL"'),
    ('Andorra', '"AD"'),
    ('United Arab Emirates', '"AE"'),
    ('Afghanistan', '"AF"'),
    ('Antigua and Barbuda', '"AG"'),
    ('Armenia', '"AM"'),
    ('Angola', '"AO"'),
    ('Argentina', '"AR"'),
    ('Austria', '"AT"'),
    ('Australia', '"AU"'),
    ('Azerbaijan', '"AZ"'),
    ('Bosnia and Herzegovina', '"BA"'),
    ('Barbados', '"BB"'),
    ('Bangladesh', '"BD"'),
    ('Belgium', '"BE"'),
    ('Burkina Faso', '"BF"'),
    ('Bulgaria', '"BG"'),
    ('Bahrain', '"BH"'),
    ('Burundi', '"BI"'),
    ('Benin', '"BJ"'),
    ('Brunei Darussalam', '"BN"'),
    ('Bolivia, Plurinational State of', '"BO"'),
    ('Brazil', '"BR"'),
    ('Bahamas', '"BS"'),
    ('Bhutan', '"BT"'),
    ('Botswana', '"BW"'),
    ('Belarus', '"BY"'),
    ('Belize', '"BZ"'),
    ('Canada', '"CA"'),
    ('Congo, Democratic Republic of the', '"CD"'),
    ('Central African Republic', '"CF"'),
    ('Congo', '"CG"'),
    ('Switzerland', '"CH"'),
    ('Côte ''Ivoire', '"CI"'),
    ('Chile', '"CL"'),
    ('Cameroon', '"CM"'),
    ('China', '"CN"'),
    ('Colombia', '"CO"'),
    ('Costa Rica', '"CR"'),
    ('Cuba', '"CU"'),
    ('Cabo Verde', '"CV"'),
    ('Cyprus', '"CY"'),
    ('Czechia', '"CZ"'),
    ('Germany', '"DE"'),
    ('Djibouti', '"DJ"'),
    ('Denmark', '"DK"'),
    ('Dominica', '"DM"'),
    ('Dominican Republic', '"DO"'),
    ('Algeria', '"DZ"'),
    ('Ecuador', '"EC"'),
    ('Estonia', '"EE"'),
    ('Egypt', '"EG"'),
    ('Western Sahara', '"EH"'),
    ('Eritrea', '"ER"'),
    ('Spain', '"ES"'),
    ('Ethiopia', '"ET"'),
    ('Finland', '"FI"'),
    ('Fiji', '"FJ"'),
    ('Micronesia, Federated States of', '"FM"'),
    ('France', '"FR"'),
    ('Gabon', '"GA"'),
    ('United Kingdom', '"GB"'),
    ('Grenada', '"GD"'),
    ('Georgia', '"GE"'),
    ('Ghana', '"GH"'),
    ('Gambia', '"GM"'),
    ('Guinea', '"GN"'),
    ('Equatorial Guinea', '"GQ"'),
    ('Greece', '"GR"'),
    ('Guatemala', '"GT"'),
    ('Guinea-Bissau', '"GW"'),
    ('Guyana', '"GY"'),
    ('Guernsey', '"GG"'),
    ('Hong Kong', '"HK"'),
    ('Honduras', '"HN"'),
    ('Croatia', '"HR"'),
    ('Haiti', '"HT"'),
    ('Hungary', '"HU"'),
    ('Indonesia', '"ID"'),
    ('Ireland', '"IE"'),
    ('Israel', '"IL"'),
    ('India', '"IN"'),
    ('Iraq', '"IQ"'),
    ('Iran, Islamic Republic of', '"IR"'),
    ('Iceland', '"IS"'),
    ('Italy', '"IT"'),
    ('Isle of Man', '"IM"'),
    ('Jamaica', '"JM"'),
    ('Jersey', '"JE"'),
    ('Jordan', '"JO"'),
    ('Japan', '"JP"'),
    ('Kenya', '"KE"'),
    ('Kyrgyzstan', '"KG"'),
    ('Cambodia', '"KH"'),
    ('Kiribati', '"KI"'),
    ('Comoros', '"KM"'),
    ('Saint Kitts and Nevis', '"KN"'),
    ('Korea, Democratic People''s Republic of', '"KP"'),
    ('Korea, Republic of', '"KR"'),
    ('Kuwait', '"KW"'),
    ('Cayman Islands', '"KY"'),
    ('Kazakhstan', '"KZ"'),
    ('Lao People''s Democratic Republic', '"LA"'),
    ('Lebanon', '"LB"'),
    ('Saint Lucia', '"LC"'),
    ('Liechtenstein', '"LI"'),
    ('Sri Lanka', '"LK"'),
    ('Liberia', '"LR"'),
    ('Lesotho', '"LS"'),
    ('Lithuania', '"LT"'),
    ('Luxembourg', '"LU"'),
    ('Latvia', '"LV"'),
    ('Libya', '"LY"'),
    ('Morocco', '"MA"'),
    ('Monaco', '"MC"'),
    ('Moldova, Republic of', '"MD"'),
    ('Montenegro', '"ME"'),
    ('Madagascar', '"MG"'),
    ('Marshall Islands', '"MH"'),
    ('North Macedonia', '"MK"'),
    ('Mali', '"ML"'),
    ('Myanmar', '"MM"'),
    ('Mongolia', '"MN"'),
    ('Mauritania', '"MR"'),
    ('Malta', '"MT"'),
    ('Mauritius', '"MU"'),
    ('Maldives', '"MV"'),
    ('Malawi', '"MW"'),
    ('Mexico', '"MX"'),
    ('Malaysia', '"MY"'),
    ('Mozambique', '"MZ"'),
    ('Namibia', '"NA"'),
    ('Niger', '"NE"'),
    ('Nigeria', '"NG"'),
    ('Nicaragua', '"NI"'),
    ('Netherlands', '"NL"'),
    ('Norway', '"NO"'),
    ('Nepal', '"NP"'),
    ('Nauru', '"NR"'),
    ('New Zealand', '"NZ"'),
    ('Oman', '"OM"'),
    ('Panama', '"PA"'),
    ('Peru', '"PE"'),
    ('Papua New Guinea', '"PG"'),
    ('Philippines', '"PH"'),
    ('Pakistan', '"PK"'),
    ('Poland', '"PL"'),
    ('Portugal', '"PT"'),
    ('Palau', '"PW"'),
    ('Paraguay', '"PY"'),
    ('Qatar', '"QA"'),
    ('Romania', '"RO"'),
    ('Serbia', '"RS"'),
    ('Russian Federation', '"RU"'),
    ('Rwanda', '"RW"'),
    ('Saudi Arabia', '"SA"'),
    ('Solomon Islands', '"SB"'),
    ('Seychelles', '"SC"'),
    ('Sudan', '"SD"'),
    ('Sweden', '"SE"'),
    ('Singapore', '"SG"'),
    ('Slovenia', '"SI"'),
    ('Slovakia', '"SK"'),
    ('Sierra Leone', '"SL"'),
    ('San Marino', '"SM"'),
    ('Senegal', '"SN"'),
    ('Somalia', '"SO"'),
    ('Suriname', '"SR"'),
    ('South Sudan', '"SS"'),
    ('Sao Tome and Principe', '"ST"'),
    ('El Salvador', '"SV"'),
    ('Syrian Arab Republic', '"SY"'),
    ('Eswatini', '"SZ"'),
    ('Chad', '"TD"'),
    ('Togo', '"TG"'),
    ('Thailand', '"TH"'),
    ('Tajikistan', '"TJ"'),
    ('Timor-Leste', '"TL"'),
    ('Turkmenistan', '"TM"'),
    ('Tunisia', '"TN"'),
    ('Tonga', '"TO"'),
    ('Turkey', '"TR"'),
    ('Trinidad and Tobago', '"TT"'),
    ('Tuvalu', '"TV"'),
    ('Taiwan, Province of China', '"TW"'),
    ('Tanzania, United Republic of', '"TZ"'),
    ('Ukraine', '"UA"'),
    ('Uganda', '"UG"'),
    ('United States', '"US"'),
    ('Uruguay', '"UY"'),
    ('Uzbekistan', '"UZ"'),
    ('Holy See', '"VA"'),
    ('Saint Vincent and the Grenadines', '"VC"'),
    ('Venezuela, Bolivarian Republic of', '"VE"'),
    ('Viet Nam', '"VN"'),
    ('Vanuatu', '"VU"'),
    ('Kosovo', '"XK"'),
    ('Yemen', '"YE"'),
    ('South Africa', '"ZA"'),
    ('Zambia', '"ZM"'),
    ('Zimbabwe', '"ZW"');


UPDATE organization
SET address = jsonb_set(
    address,
    '{countryCode}',
    (SELECT iso_code
     FROM country_codes
     WHERE country_codes.country_name = address ->> 'country')::jsonb,
    true
)
WHERE address ? 'country'
  AND address ->> 'country' IS NOT NULL
  AND (
    NOT address ? 'countryCode'
    OR address ->> 'countryCode' IS NULL
  )
  AND address ->> 'country' IN (
    SELECT country_name
    FROM country_codes
  );

DROP TABLE IF EXISTS country_codes;