UPDATE course_evaluation_questions
SET required = '1'
WHERE
  question_key IN (
    'ATTITUDE_AND_APPROACH_OF_TRAINERS',
    'KNOWLEDGE_OF_SUBJECT',
    'PREPARATION_AND_ORGANISATION',
    'GROUP_PARTICIPATION',
    'WORKBOOK_AND_PRESENTATION_MATERIALS',
    'SUITABILITY_OF_TRAINING_ENVIRONMENT',
    'LUNCH_REFRESHMENTS',
    'SIGNATURE',
    'OBJECTIVES_ACHIEVED',
    'EMPHASIS_ON_DEESCALATION',
    'RISK_REDUCTION',
    'VALUE_OF_TRAINING',
    'KEY_STRENGTHS_OF_COURSE'
  )