// TODO: fix colors based on course level
// colors denote the course level, dark blue is level 1,
// purple level 2, pink is advanced and turquoise for the top level BILD ACT certification
export default [
  {
    id: '1',
    name: 'Positive Behaviour Training: Level Two',
    date: new Date(),
    orgName: 'ABC Org',
    color: 'bg-purple-500',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Positive Behaviour Training: BILD ACT Certified',
    date: new Date(),
    orgName: 'ABC Org',
    color: 'bg-teal-500',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Positive Behaviour Training: Level One',
    date: new Date(),
    orgName: 'ABC Org',
    color: 'bg-navy-500',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Positive Behaviour Training: Advanced Modules',
    date: new Date(),
    orgName: 'ABC Org',
    color: 'bg-fuschia-500',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Positive Behaviour Training: Advanced Modules',
    date: new Date(),
    orgName: 'ABC Org',
    color: 'bg-fuschia-500',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
