version: '3.6'

services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - tth-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tth-db

  graphql-engine:
    image: hasura/graphql-engine:v2.1.1.cli-migrations-v3
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:root@postgres:5432/tth-db
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ADMIN_SECRET: tth-hasura-key
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256","jwk_url":"https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_MbPqfM7i4/.well-known/jwks.json","claims_format":"stringified_json"}'
      EVENTS_HOST: 'https://vjil7l5fmc.execute-api.eu-west-2.amazonaws.com/dev'
      ACTIONS_HOST: 'https://vjil7l5fmc.execute-api.eu-west-2.amazonaws.com/dev'

volumes:
  tth-data:
