ALTER TABLE job_title ADD COLUMN IF NOT EXISTS "shard" text DEFAULT 'UK' NOT NULL;
ALTER TABLE job_title DROP CONSTRAINT IF EXISTS "job_title_title_key";

INSERT INTO job_title (title, shard) VALUES
(E'Assistant Director of Nursing', 'ANZ'),
(E'Administrator', 'ANZ'),
(E'Assistant Headteacher/Principal', 'ANZ'),
(E'Behaviour Lead', 'ANZ'),
(E'Bursar', 'ANZ'),
(E'Behaviour Support Practitioner', 'ANZ'),
(E'Business Support', 'ANZ'),
(E'Care Assistant', 'ANZ'),
(E'Care Coordinator', 'ANZ'),
(E'Careers Advisor', 'ANZ'),
(E'Carer', 'ANZ'),
(E'Case Manager', 'ANZ'),
(E'CEO', 'ANZ'),
(E'Children\'s Commissioner', 'ANZ'),
(E'Clinical Commissioner', 'ANZ'),
(E'Community Support Worker', 'ANZ'),
(E'Compliance & Standards Manager', 'ANZ'),
(E'Counsellor', 'ANZ'),
(E'Cover/Relief Supervisor', 'ANZ'),
(E'Deputy Headteacher/Principal', 'ANZ'),
(E'Deputy Manager', 'ANZ'),
(E'Designated Safeguarding Lead ', 'ANZ'),
(E'Director', 'ANZ'),
(E'Director of Nursing', 'ANZ'),
(E'Director of Social Services', 'ANZ'),
(E'Early Intervention & Protection', 'ANZ'),
(E'Education Support', 'ANZ'),
(E'Educational Mental Health Practitioner', 'ANZ'),
(E'Educational Psychologist', 'ANZ'),
(E'Family Support Worker', 'ANZ'),
(E'Foster Carer', 'ANZ'),
(E'Guidance Councillor', 'ANZ'),
(E'Head of School', 'ANZ'),
(E'Head of Year', 'ANZ'),
(E'Headteacher/Principal', 'ANZ'),
(E'Home\'s Manager', 'ANZ'),
(E'HR Director', 'ANZ'),
(E'HR Manager', 'ANZ'),
(E'Inclusion Manager', 'ANZ'),
(E'Learning & Development Manager', 'ANZ'),
(E'Learning Mentor', 'ANZ'),
(E'Learning Support', 'ANZ'),
(E'Lunchtime Supervisor', 'ANZ'),
(E'Night Care Assistant', 'ANZ'),
(E'Night Officer', 'ANZ'),
(E'NQT (Newly Qualified Teacher)', 'ANZ'),
(E'Nursery/Kindergarten/Pre-school Manager', 'ANZ'),
(E'Nursery/Kindergarten/Pre-school Worker', 'ANZ'),
(E'Nursing Lead', 'ANZ'),
(E'Office Manager', 'ANZ'),
(E'Operations Manager', 'ANZ'),
(E'OSHC (Outdside School Hours Club) Manager', 'ANZ'),
(E'OSHC (Outdside School Hours Club) Worker', 'ANZ'),
(E'Owner', 'ANZ'),
(E'Pastoral Manager', 'ANZ'),
(E'Playleader', 'ANZ'),
(E'Recruitment Consultant', 'ANZ'),
(E'Regional Manager', 'ANZ'),
(E'Registered Manager', 'ANZ'),
(E'Residential Support Worker', 'ANZ'),
(E'Residential Worker', 'ANZ'),
(E'RI (Responsible Individual)', 'ANZ'),
(E'Safeguarding Lead', 'ANZ'),
(E'Safeguarding Officer', 'ANZ'),
(E'School Business Manager', 'ANZ'),
(E'Secretary', 'ANZ'),
(E'SENCO/HOSES', 'ANZ'),
(E'Service Manager', 'ANZ'),
(E'Specialist Co-ordinator (Adults)', 'ANZ'),
(E'Sports Coach', 'ANZ'),
(E'Student Support', 'ANZ'),
(E'Support Worker', 'ANZ'),
(E'TA (Teaching Assistant)/LSA(Learning Support Assistant)/Education Assistant', 'ANZ'),
(E'Teacher', 'ANZ'),
(E'Team Manager', 'ANZ'),
(E'Training Administrator', 'ANZ'),
(E'Training Co-ordinator', 'ANZ'),
(E'Training & Development', 'ANZ'),
(E'Training Manager', 'ANZ'),
(E'Tutor', 'ANZ'),
(E'Unemployed', 'ANZ'),
(E'Unit Manager', 'ANZ'),
(E'Unqualified Teacher', 'ANZ'),
(E'Vice Principal', 'ANZ'),
(E'Volunteer', 'ANZ'),
(E'Welfare Assistant', 'ANZ'),
(E'Wellbeing Co-ordinator', 'ANZ'),
(E'Workforce Development', 'ANZ'),
(E'Year Leader', 'ANZ'),
(E'Youth Offending Service', 'ANZ'),
(E'Youth Worker', 'ANZ'),
(E'Other', 'ANZ');