INSERT INTO "public"."organization_type"("name", "sector", "nonUK") VALUES 
(E'International Primary', E'EDU', true),
(E'International Secondary', E'EDU', true),
(E'International 3 - 18', E'EDU', true),
(E'International Special', E'EDU', true),
(E'Acquired Brain Injury', E'HSC_ADULT', true),
(E'Adult Day Services', E'HSC_ADULT', true),
(E'Dementia / Alzheimer\'s', E'HSC_ADULT', true),
(E'Healthcare', E'HSC_ADULT', true),
(E'Learning Disabilities', E'HSC_ADULT', true),
(E'Long Term Care Services', E'HSC_ADULT', true),
(E'Mental Health Services', E'HSC_ADULT', true),
(E'Older Adults', E'HSC_ADULT', true),
(E'Rehabilitation Settings', E'HSC_ADULT', true),
(E'Residential Services', E'HSC_ADULT', true),
(E'Short Breaks', E'HSC_ADULT', true),
(E'Social Care', E'HSC_ADULT', true),
(E'Substance Misuse Services', E'HSC_ADULT', true),
(E'Supported Living', E'HSC_ADULT', true),
(E'CAMHS', E'HSC_CHILDREN', true),
(E'Children\'s Homes', E'HSC_CHILDREN', true),
(E'Early Years', E'HSC_CHILDREN', true),
(E'Foster Care', E'HSC_CHILDREN', true),
(E'Healthcare', E'HSC_CHILDREN', true),
(E'Residential Services', E'HSC_CHILDREN', true),
(E'Short Breaks', E'HSC_CHILDREN', true),
(E'Social Care', E'HSC_CHILDREN', true),
(E'Specialist Learning Disability Services', E'HSC_CHILDREN', true),
(E'Supported Living', E'HSC_CHILDREN', true),
(E'Youth Justice', E'HSC_CHILDREN', true);
