DELETE FROM public.go1_history_events 
WHERE name in (
    'LICENSES_ADDED', 
    'LICENSES_REMOVED',
    'LICENSE_REVOKED',
    'LICENSES_RELEASED',
    'LICENSE_ISSUED',
    'LICENSES_PURCHASED'
);
