INSERT INTO "public"."job_title"("title") VALUES
(E'1:1 TA (Support)'),
(E'Administrator'),
(E'Assistant Director of Nursing'),
(E'Assistant Headteacher'),
(E'Behaviour Lead'),
(E'Bursar'),
(E'Business Support'),
(E'Care Assistant'),
(E'Care Coordinator'),
(E'Careers Advisor'),
(E'Carer'),
(E'Case Manager'),
(E'CEO'),
(E'Clinical Commissioner'),
(E'Community Support Worker'),
(E'Compliance & Standards Manager'),
(E'Counsellor'),
(E'Cover Supervisor'),
(E'Deputy Headteacher'),
(E'Deputy Manager'),
(E'Designated Safeguarding Lead'),
(E'Director'),
(E'Director of Nursing'),
(E'Director of Social Services'),
(E'Early Intervention & Protection'),
(E'Educational Mental Health Practitioner'),
(E'Educational Psychologist'),
(E'EYFS Practitioner'),
(E'Family Support Worker'),
(E'Foster Carer'),
(E'Head of School'),
(E'Head of Year'),
(E'Headteacher'),
(E'HLTA'),
(E'HR Director'),
(E'HR Manager'),
(E'Inclusion Manager'),
(E'Learning & Development Manager'),
(E'Learning Mentor'),
(E'LSA (Learning Support Assistant),'),
(E'Lunchtime Supervisor'),
(E'Night Care Assistant'),
(E'Night Officer'),
(E'NQT (Newly Qualified Teacher),'),
(E'Nursery Manager'),
(E'Nursery Nurse'),
(E'Nursery Worker'),
(E'Nursing Lead'),
(E'Office Manager'),
(E'Operations Manager'),
(E'Owner'),
(E'Pastoral Manager'),
(E'Playleader'),
(E'Principal'),
(E'Recruitment Consultant'),
(E'Regional Manager'),
(E'Registered Manager'),
(E'Residential Support Worker'),
(E'Residential Worker'),
(E'RI (Responsible Individual),'),
(E'Safeguarding Lead'),
(E'Safeguarding Officer'),
(E'School Business Manager'),
(E'Secretary'),
(E'SENCO'),
(E'Service Manager'),
(E'SNA'),
(E'Specialist Co-ordinator (Adults),'),
(E'Sports Coach'),
(E'Support Worker'),
(E'TA (Teaching Assistant),'),
(E'Teacher'),
(E'Team Manager'),
(E'Training & Development'),
(E'Training Administrator'),
(E'Training Co-ordinator'),
(E'Training Manager'),
(E'Tutor'),
(E'Unemployed'),
(E'Unit Manager'),
(E'Unqualified Teacher'),
(E'Vice Principal'),
(E'Volunteer'),
(E'Welfare Assistant'),
(E'Wellbeing Co-ordinator'),
(E'Workforce Development'),
(E'Year Leader'),
(E'Youth Offending Service'),
(E'Youth Worker'),
(E'Children\'s Commissioner'),
(E'Home\'s Manager')