INSERT INTO public.course_status ("name") VALUES 
('TRAINER_PENDING'),
('TRAINER_UNAVAILABLE'),
('CANCELLED'),
('DECLINED'),
('GRADE_MISSING'),
('EVALUATION_MISSING'),
('COMPLETED'),
('APPROVAL_PENDING');
