
INSERT INTO module_group (name,created_at, mandatory, course_level, color) VALUES 
('Theory','2023-12-14T07:00:00.121193+00:00','true','THREE_DAY_SAFETY_RESPONSE_TRAINER','navy'),
('Personal Space & Body Language','2023-12-14T07:00:00.121194+00:00','true','THREE_DAY_SAFETY_RESPONSE_TRAINER','navy'),
('Elevated Risk','2023-12-14T07:00:00.121195+00:00','true','THREE_DAY_SAFETY_RESPONSE_TRAINER','navy'),
('Physical Warm up','2023-12-14T07:00:00.121196+00:00','true','THREE_DAY_SAFETY_RESPONSE_TRAINER','navy'),
('Personal Safety - Assess Risk, Reduce Risk, Gates','2023-12-14T07:00:00.121197+00:00','true','THREE_DAY_SAFETY_RESPONSE_TRAINER','navy'),
('Prompts, Guides & Separations','2023-12-14T07:00:00.121198+00:00','true','THREE_DAY_SAFETY_RESPONSE_TRAINER','navy');

INSERT INTO module_group_duration (module_group_id, course_delivery_type, duration)
VALUES  ((SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'F2F',90),
        ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'F2F',90),
        ((SELECT id FROM module_group WHERE name = 'Elevated Risk' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'F2F',90),
        ((SELECT id FROM module_group WHERE name = 'Physical Warm up' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'F2F',90),
        ((SELECT id FROM module_group WHERE name = 'Personal Safety - Assess Risk, Reduce Risk, Gates' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'F2F',90),
        ((SELECT id FROM module_group WHERE name = 'Prompts, Guides & Separations' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'F2F',90);

INSERT INTO module (name, module_category, module_group_id, course_level) VALUES
('The Why','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Values activity','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('The Infinity Cycle','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Functions of behaviour','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Behaviours of communication','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Effective and less effective practice','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Legal framework','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Risk assessment','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Policies, practices & procedures','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Stages of distress and support','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Conflict spiral','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Cycle of influence','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Fizzy Pop challenge','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Individual support plans','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Listening and learning','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Quiz','THEORY',(SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),        
('Circles of awareness and danger','THEORY',(SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Posturing, non-verbal and verbal communication','THEORY',(SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Calm  stance','THEORY',(SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Calming scripts','THEORY',(SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),        
('Positional asphyxia & hyper flexion','THEORY',(SELECT id FROM module_group WHERE name = 'Elevated Risk' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Pressure on abdomen and ribcage','THEORY',(SELECT id FROM module_group WHERE name = 'Elevated Risk' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Leaning forward','THEORY',(SELECT id FROM module_group WHERE name = 'Elevated Risk' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Prone restraint','THEORY',(SELECT id FROM module_group WHERE name = 'Elevated Risk' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),        
('Pulse raisers','THEORY',(SELECT id FROM module_group WHERE name = 'Physical Warm up' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Stretches','THEORY',(SELECT id FROM module_group WHERE name = 'Physical Warm up' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Rowboat and ride bike','THEORY',(SELECT id FROM module_group WHERE name = 'Physical Warm up' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Pass ball','THEORY',(SELECT id FROM module_group WHERE name = 'Physical Warm up' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Sensitivity of fingers','THEORY',(SELECT id FROM module_group WHERE name = 'Physical Warm up' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Circle of friends','THEORY',(SELECT id FROM module_group WHERE name = 'Physical Warm up' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),        
('Show and go','THEORY',(SELECT id FROM module_group WHERE name = 'Prompts, Guides & Separations' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Caring C guide','THEORY',(SELECT id FROM module_group WHERE name = 'Prompts, Guides & Separations' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Steering away','THEORY',(SELECT id FROM module_group WHERE name = 'Prompts, Guides & Separations' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Punches and kicks','THEORY',(SELECT id FROM module_group WHERE name = 'Prompts, Guides & Separations' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Arm responses','THEORY',(SELECT id FROM module_group WHERE name = 'Personal Safety - Assess Risk, Reduce Risk, Gates' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Neck responses','THEORY',(SELECT id FROM module_group WHERE name = 'Personal Safety - Assess Risk, Reduce Risk, Gates' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Clothing and hair responses','THEORY',(SELECT id FROM module_group WHERE name = 'Personal Safety - Assess Risk, Reduce Risk, Gates' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER');


INSERT INTO submodule(name,module_category,module_id,course_level) VALUES
('Side step in','THEORY',(SELECT id FROM module WHERE name = 'Arm responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Drop elbow','THEORY',(SELECT id FROM module WHERE name = 'Arm responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Pump','THEORY',(SELECT id FROM module WHERE name = 'Arm responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Conductor','THEORY',(SELECT id FROM module WHERE name = 'Arm responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Click','THEORY',(SELECT id FROM module WHERE name = 'Arm responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Steering wheel','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Fix and stabilise','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Windmill','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Snake','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Elbow swing','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Neck brace','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Bar and brace - behind','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Elbow guide out of headlock','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Spin out of strangle','THEORY',(SELECT id FROM module WHERE name = 'Neck responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Fix and stabilise','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Closed fist hold','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Tube grip','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Close to the neck','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('From behind','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('One handed hold','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Two handed hold','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Oyster','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Knuckle roll','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER'),
('Knuckle slide','THEORY',(SELECT id FROM module WHERE name = 'Clothing and hair responses' AND course_level = 'THREE_DAY_SAFETY_RESPONSE_TRAINER'),'THREE_DAY_SAFETY_RESPONSE_TRAINER');
