-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE "organization_member" (
--   "id" uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid (),
--   "profile_id" uuid NOT NULL REFERENCES "profile" ("id") ON DELETE CASCADE,
--   "organization_id" uuid NOT NULL REFERENCES "organization" ("id") ON DELETE CASCADE,
--   "member_type" varchar,
--   "_source" varchar,
--   "created_at" timestamptz NOT NULL DEFAULT NOW(),
--   "updated_at" timestamptz NOT NULL DEFAULT NOW(),
--   UNIQUE ("profile_id", "organization_id")
-- );
--
-- CREATE INDEX "organization_member_profile_id_idx" ON "organization_member" ("profile_id");
