INSERT INTO module_setting(course_level, course_delivery_type, course_type, go1_integration, reaccreditation, module_name, mandatory, color, duration, sort)
VALUES 
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Personal Safety', true, 'navy', 30, 5),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Prompts and Guides', true, 'navy', 20, 6),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Clothing Responses', true, 'navy', 20, 7),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Hair Responses', true, 'navy', 20, 8),
  ('LEVEL_1', 'F2F', 'OPEN', false, false, 'Bite Responses', true, 'navy', 20, 9),

  ('LEVEL_1', 'VIRTUAL', 'OPEN', false, false, 'Theory', true, 'navy', 240, 1),
  ('LEVEL_1', 'VIRTUAL', 'OPEN', false, false, 'Personal Space & Body Language', true, 'navy', 120, 2),

  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_1', 'F2F', 'CLOSED', false, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),

  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Theory', true, 'navy', 30, 1),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Personal Space & Body Language', true, 'navy', 30, 2),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_1', 'F2F', 'CLOSED', true, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),

  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'F2F', 'CLOSED', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'F2F', 'CLOSED', true, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, false, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'MIXED', 'CLOSED', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, false, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'VIRTUAL', 'CLOSED', true, false, 'Theory', true, 'navy', 30, 1),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', true, false, 'Personal Space & Body Language', true, 'navy', 30, 2),
  
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'VIRTUAL', 'CLOSED', true, true, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_1', 'VIRTUAL', 'CLOSED', true, true, 'Personal Space & Body Language', true, 'navy', 60, 2),

  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),

  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Theory', true, 'navy', 30, 1),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Personal Space & Body Language', true, 'navy', 30, 2),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),

  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'F2F', 'INDIRECT', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'F2F', 'INDIRECT', true, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, false, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Physical Warm Up', false, 'navy', 15, 4),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Neck Disengagement', false, 'navy', 20, 6),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_1', 'MIXED', 'INDIRECT', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),

  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Personal Safety', true, 'navy', 30, 5),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Neck Disengagement', true, 'navy', 30, 6),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Prompts and Guides', true, 'navy', 20, 7),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Separations', true, 'navy', 20, 8),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Clothing Responses', true, 'navy', 20, 9),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Hair Responses', true, 'navy', 20, 10),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Bite Responses', true, 'navy', 20, 11),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Small Child and One Person Holds', true, 'navy', 60, 12),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Seated Holds', true, 'purple', 90, 12),
  ('LEVEL_2', 'F2F', 'OPEN', false, false, 'Two Person Escorts', true, 'purple', 90, 12),

  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Personal Safety', true, 'navy', 20, 5),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Neck Disengagement', true, 'navy', 20, 6),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Prompts and Guides', true, 'navy', 15, 7),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Separations', true, 'navy', 15, 8),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Clothing Responses', true, 'navy', 15, 9),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Hair Responses', true, 'navy', 15, 10),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Bite Responses', true, 'navy', 15, 11),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Small Child and One Person Holds', true, 'navy', 30, 12),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Seated Holds', true, 'purple', 45, 12),
  ('LEVEL_2', 'F2F', 'OPEN', false, true, 'Two Person Escorts', true, 'purple', 45, 12),

  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Personal Safety', true, 'navy', 30, 5),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Neck Disengagement', true, 'navy', 30, 6),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Prompts and Guides', true, 'navy', 20, 7),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Separations', true, 'navy', 20, 8),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Clothing Responses', true, 'navy', 20, 9),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Hair Responses', true, 'navy', 20, 10),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Bite Responses', true, 'navy', 20, 11),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Small Child and One Person Holds', true, 'navy', 60, 12),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Seated Holds', true, 'purple', 90, 12),
  ('LEVEL_2', 'MIXED', 'OPEN', false, false, 'Two Person Escorts', true, 'purple', 90, 12),

  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Personal Safety', true, 'navy', 20, 5),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Neck Disengagement', true, 'navy', 20, 6),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Prompts and Guides', true, 'navy', 15, 7),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Separations', true, 'navy', 15, 8),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Clothing Responses', true, 'navy', 15, 9),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Hair Responses', true, 'navy', 15, 10),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Bite Responses', true, 'navy', 15, 11),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Small Child and One Person Holds', true, 'navy', 30, 12),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Seated Holds', true, 'purple', 45, 12),
  ('LEVEL_2', 'MIXED', 'OPEN', false, true, 'Two Person Escorts', true, 'purple', 45, 12),

  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Seated Holds', false, 'purple', 90, 12),
  ('LEVEL_2', 'F2F', 'CLOSED', false, false, 'Two Person Escorts', false, 'purple', 90, 12),

  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Seated Holds', false, 'purple', 45, 12),
  ('LEVEL_2', 'F2F', 'CLOSED', false, true, 'Two Person Escorts', false, 'purple', 45, 12),

  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Seated Holds', false, 'purple', 90, 12),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, false, 'Two Person Escorts', false, 'purple', 90, 12),

  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Seated Holds', false, 'purple', 45, 12),
  ('LEVEL_2', 'MIXED', 'CLOSED', false, true, 'Two Person Escorts', false, 'purple', 45, 12),

  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Seated Holds', false, 'purple', 90, 12),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, false, 'Two Person Escorts', false, 'purple', 90, 12),

  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Seated Holds', false, 'purple', 45, 12),
  ('LEVEL_2', 'F2F', 'INDIRECT', false, true, 'Two Person Escorts', false, 'purple', 45, 12),

  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Theory', true, 'navy', 180, 1),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Personal Safety', false, 'navy', 30, 5),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Prompts and Guides', false, 'navy', 20, 7),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Separations', false, 'navy', 20, 8),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Clothing Responses', false, 'navy', 20, 9),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Hair Responses', false, 'navy', 20, 10),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Bite Responses', false, 'navy', 20, 11),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Small Child and One Person Holds', false, 'navy', 60, 12),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Seated Holds', false, 'purple', 90, 12),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, false, 'Two Person Escorts', false, 'purple', 90, 12),

  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Theory', true, 'navy', 90, 1),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Personal Safety', false, 'navy', 20, 5),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Neck Disengagement', false, 'navy', 30, 6),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Prompts and Guides', false, 'navy', 15, 7),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Separations', false, 'navy', 15, 8),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Clothing Responses', false, 'navy', 15, 9),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Hair Responses', false, 'navy', 15, 10),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Bite Responses', false, 'navy', 15, 11),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Small Child and One Person Holds', false, 'navy', 30, 12),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Seated Holds', false, 'purple', 45, 12),
  ('LEVEL_2', 'MIXED', 'INDIRECT', false, true, 'Two Person Escorts', false, 'purple', 45, 12),

  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Theory', true, 'navy', 180, 1),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Personal Safety', true, 'navy', 30, 5),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Neck Disengagement', true, 'navy', 30, 6),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Prompts and Guides', true, 'navy', 20, 7),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Separations', true, 'navy', 20, 8),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Clothing Responses', true, 'navy', 20, 9),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Hair Responses', true, 'navy', 20, 10),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Bite Responses', true, 'navy', 20, 11),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Small Child and One Person Holds', true, 'navy', 60, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Seated Holds', true, 'purple', 90, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, false, 'Two Person Escorts', true, 'purple', 90, 12),
  
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Theory', true, 'navy', 90, 1),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Personal Safety', true, 'navy', 20, 5),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Neck Disengagement', true, 'navy', 20, 6),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Prompts and Guides', true, 'navy', 15, 7),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Separations', true, 'navy', 15, 8),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Clothing Responses', true, 'navy', 15, 9),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Hair Responses', true, 'navy', 15, 10),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Bite Responses', true, 'navy', 15, 11),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Small Child and One Person Holds', true, 'navy', 30, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Seated Holds', true, 'purple', 45, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'OPEN', false, true, 'Two Person Escorts', true, 'purple', 45, 12),

  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Theory', true, 'navy', 180, 1),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Physical Warm Up', true, 'navy', 30, 4),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Personal Safety', true, 'navy', 30, 5),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Neck Disengagement', true, 'navy', 30, 6),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Prompts and Guides', true, 'navy', 20, 7),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Separations', true, 'navy', 20, 8),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Clothing Responses', true, 'navy', 20, 9),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Hair Responses', true, 'navy', 20, 10),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Bite Responses', true, 'navy', 20, 11),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Small Child and One Person Holds', true, 'navy', 60, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Seated Holds', true, 'purple', 90, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, false, 'Two Person Escorts', true, 'purple', 90, 12),
  
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Theory', true, 'navy', 90, 1),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Personal Space & Body Language', true, 'navy', 60, 2),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Elevated Risks', true, 'navy', 15, 3),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Physical Warm Up', true, 'navy', 15, 4),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Personal Safety', true, 'navy', 20, 5),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Neck Disengagement', true, 'navy', 20, 6),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Prompts and Guides', true, 'navy', 15, 7),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Separations', true, 'navy', 15, 8),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Clothing Responses', true, 'navy', 15, 9),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Hair Responses', true, 'navy', 15, 10),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Bite Responses', true, 'navy', 15, 11),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Small Child and One Person Holds', true, 'navy', 30, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Seated Holds', true, 'purple', 45, 12),
  ('INTERMEDIATE_TRAINER', 'F2F', 'CLOSED', false, true, 'Two Person Escorts', true, 'purple', 45, 12),

  ('ADVANCED', 'F2F', 'CLOSED', false, false, 'Advanced Warm Up', true, 'fuschia', 15, 1),
  ('ADVANCED', 'F2F', 'CLOSED', false, false, 'Legal & Health', true, 'fuschia', 20, 2),
  ('ADVANCED', 'F2F', 'CLOSED', false, false, 'Additional Ground Responses', false, 'fuschia', 30, 3),
  ('ADVANCED', 'F2F', 'CLOSED', false, false, 'Everyday Objects used as Weapons', false, 'fuschia', 120, 4),
  ('ADVANCED', 'F2F', 'CLOSED', false, false, 'Ground Recovery Safeguards', false, 'fuschia', 120, 5),
  ('ADVANCED', 'F2F', 'CLOSED', false, false, 'Transport', false, 'fuschia', 40, 6),

  ('ADVANCED', 'F2F', 'INDIRECT', false, false, 'Advanced Warm Up', true, 'fuschia', 15, 1),
  ('ADVANCED', 'F2F', 'INDIRECT', false, false, 'Legal & Health', true, 'fuschia', 20, 2),
  ('ADVANCED', 'F2F', 'INDIRECT', false, false, 'Additional Ground Responses', false, 'fuschia', 30, 3),
  ('ADVANCED', 'F2F', 'INDIRECT', false, false, 'Everyday Objects used as Weapons', false, 'fuschia', 120, 4),
  ('ADVANCED', 'F2F', 'INDIRECT', false, false, 'Ground Recovery Safeguards', false, 'fuschia', 120, 5),
  ('ADVANCED', 'F2F', 'INDIRECT', false, false, 'Transport', false, 'fuschia', 40, 6),

  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, false, 'Refresh of Intermediate Techniques', true, 'fuschia', 30, 1),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, false, 'Additional Ground Responses', true, 'fuschia', 30, 2),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, false, 'Advanced Warm Up', true, 'fuschia', 15, 3),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, false, 'Everyday Objects used as Weapons', true, 'fuschia', 120, 4),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, false, 'Ground Recovery Safeguards', true, 'fuschia', 120, 5),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, false, 'Legal & Health', true, 'fuschia', 20, 6),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, false, 'Transport', true, 'fuschia', 40, 7),

  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, true, 'Refresh of Intermediate Techniques', true, 'fuschia', 30, 1),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, true, 'Additional Ground Responses', true, 'fuschia', 30, 2),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, true, 'Advanced Warm Up', true, 'fuschia', 15, 3),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, true, 'Everyday Objects used as Weapons', true, 'fuschia', 120, 4),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, true, 'Ground Recovery Safeguards', true, 'fuschia', 120, 5),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, true, 'Legal & Health', true, 'fuschia', 20, 6),
  ('ADVANCED_TRAINER', 'F2F', 'OPEN', false, true, 'Transport', true, 'fuschia', 40, 7),

  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, false, 'Refresh of Intermediate Techniques', true, 'fuschia', 30, 1),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, false, 'Additional Ground Responses', true, 'fuschia', 30, 2),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, false, 'Advanced Warm Up', true, 'fuschia', 15, 3),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, false, 'Everyday Objects used as Weapons', true, 'fuschia', 120, 4),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, false, 'Ground Recovery Safeguards', true, 'fuschia', 120, 5),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, false, 'Legal & Health', true, 'fuschia', 20, 6),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, false, 'Transport', true, 'fuschia', 40, 7),

  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, true, 'Refresh of Intermediate Techniques', true, 'fuschia', 30, 1),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, true, 'Additional Ground Responses', true, 'fuschia', 30, 2),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, true, 'Advanced Warm Up', true, 'fuschia', 15, 3),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, true, 'Everyday Objects used as Weapons', true, 'fuschia', 120, 4),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, true, 'Ground Recovery Safeguards', true, 'fuschia', 120, 5),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, true, 'Legal & Health', true, 'fuschia', 20, 6),
  ('ADVANCED_TRAINER', 'F2F', 'CLOSED', false, true, 'Transport', true, 'fuschia', 40, 7),

  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, false, 'Three Day Safety Response Trainer Theory', true, 'navy', 30, 1),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, false, 'Three Day Safety Response Personal Space & Body Language', true, 'navy', 30, 2),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, false, 'Three Day Safety Response Physical Warm Up', true, 'navy', 30, 4),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, false, 'Personal Safety - Assess Risk, Reduce Risk, Gates', true, 'navy', 30, 5),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, false, 'Prompts, Guides & Separations', true, 'navy', 30, 6),

  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, true, 'Three Day Safety Response Trainer Theory', true, 'navy', 30, 1),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, true, 'Three Day Safety Response Personal Space & Body Language', true, 'navy', 30, 2),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, true, 'Elevated Risks', true, 'navy', 30, 3),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, true, 'Three Day Safety Response Physical Warm Up', true, 'navy', 30, 4),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, true, 'Personal Safety - Assess Risk, Reduce Risk, Gates', true, 'navy', 30, 5),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'F2F', 'OPEN', false, true, 'Prompts, Guides & Separations', true, 'navy', 30, 6),

  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, false, 'Three Day Safety Response Trainer Theory', true, 'navy', 30, 1),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, false, 'Three Day Safety Response Personal Space & Body Language', true, 'navy', 30, 2),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, false, 'Elevated Risks', true, 'navy', 30, 3),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, false, 'Three Day Safety Response Physical Warm Up', true, 'navy', 30, 4),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, false, 'Personal Safety - Assess Risk, Reduce Risk, Gates', true, 'navy', 30, 5),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, false, 'Prompts, Guides & Separations', true, 'navy', 30, 6),

  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, true, 'Three Day Safety Response Trainer Theory', true, 'navy', 30, 1),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, true, 'Three Day Safety Response Personal Space & Body Language', true, 'navy', 30, 2),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, true, 'Elevated Risks', true, 'navy', 30, 3),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, true, 'Three Day Safety Response Physical Warm Up', true, 'navy', 30, 4),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, true, 'Personal Safety - Assess Risk, Reduce Risk, Gates', true, 'navy', 30, 5),
  ('THREE_DAY_SAFETY_RESPONSE_TRAINER', 'MIXED', 'OPEN', false, true, 'Prompts, Guides & Separations', true, 'navy', 30, 6);