
INSERT INTO module_setting("course_level", "reaccreditation", "go1_integration", "color", "duration", "course_delivery_type", "course_type", "module_name", "sort", "mandatory", "conversion", "shard") VALUES
-- OPEN
    -- F2F
            ('LEVEL_2', false, true, 'navy', 60, 'F2F','OPEN', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 180, 'F2F','OPEN', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'F2F','OPEN', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'F2F','OPEN', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'F2F','OPEN', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'F2F','OPEN', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'F2F','OPEN', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'F2F','OPEN', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'F2F','OPEN', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'F2F','OPEN', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'F2F','OPEN', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'F2F','OPEN', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'F2F','OPEN', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'F2F','OPEN', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'F2F','OPEN', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'F2F','OPEN', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'F2F','OPEN', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'F2F','OPEN', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'F2F','OPEN', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'F2F','OPEN', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'F2F','OPEN', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'F2F','OPEN', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

    -- VIRTUAL
            ('LEVEL_2', false, true, 'navy', 180, 'VIRTUAL','OPEN', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'VIRTUAL','OPEN', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'VIRTUAL','OPEN', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'VIRTUAL','OPEN', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'VIRTUAL','OPEN', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'VIRTUAL','OPEN', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'VIRTUAL','OPEN', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'VIRTUAL','OPEN', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'VIRTUAL','OPEN', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'VIRTUAL','OPEN', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'VIRTUAL','OPEN', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

          
            ('LEVEL_2', true, true, 'navy', 180, 'VIRTUAL','OPEN', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'VIRTUAL','OPEN', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'VIRTUAL','OPEN', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'VIRTUAL','OPEN', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'VIRTUAL','OPEN', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'VIRTUAL','OPEN', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'VIRTUAL','OPEN', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'VIRTUAL','OPEN', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'VIRTUAL','OPEN', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'VIRTUAL','OPEN', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'VIRTUAL','OPEN', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

        
    --MIXED
            ('LEVEL_2', false, true, 'navy', 180, 'MIXED','OPEN', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'MIXED','OPEN', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'MIXED','OPEN', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'MIXED','OPEN', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'MIXED','OPEN', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'MIXED','OPEN', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'MIXED','OPEN', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'MIXED','OPEN', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'MIXED','OPEN', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'MIXED','OPEN', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'MIXED','OPEN', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'MIXED','OPEN', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'MIXED','OPEN', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'MIXED','OPEN', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'MIXED','OPEN', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'MIXED','OPEN', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'MIXED','OPEN', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'MIXED','OPEN', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'MIXED','OPEN', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'MIXED','OPEN', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'MIXED','OPEN', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'MIXED','OPEN', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

--INDIRECT
    -- F2F
            ('LEVEL_2', false, true, 'navy', 180, 'F2F','INDIRECT', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'F2F','INDIRECT', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'F2F','INDIRECT', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'F2F','INDIRECT', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'F2F','INDIRECT', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'F2F','INDIRECT', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'F2F','INDIRECT', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'F2F','INDIRECT', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'F2F','INDIRECT', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'F2F','INDIRECT', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'F2F','INDIRECT', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'F2F','INDIRECT', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'F2F','INDIRECT', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'F2F','INDIRECT', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'F2F','INDIRECT', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'F2F','INDIRECT', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'F2F','INDIRECT', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'F2F','INDIRECT', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'F2F','INDIRECT', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'F2F','INDIRECT', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'F2F','INDIRECT', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'F2F','INDIRECT', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

    -- VIRTUAL
            ('LEVEL_2', false, true, 'navy', 180, 'VIRTUAL','INDIRECT', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'VIRTUAL','INDIRECT', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'VIRTUAL','INDIRECT', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'VIRTUAL','INDIRECT', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'VIRTUAL','INDIRECT', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'VIRTUAL','INDIRECT', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'VIRTUAL','INDIRECT', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'VIRTUAL','INDIRECT', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'VIRTUAL','INDIRECT', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'VIRTUAL','INDIRECT', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'VIRTUAL','INDIRECT', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'VIRTUAL','INDIRECT', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'VIRTUAL','INDIRECT', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'VIRTUAL','INDIRECT', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'VIRTUAL','INDIRECT', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'VIRTUAL','INDIRECT', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'VIRTUAL','INDIRECT', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'VIRTUAL','INDIRECT', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'VIRTUAL','INDIRECT', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'VIRTUAL','INDIRECT', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'VIRTUAL','INDIRECT', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'VIRTUAL','INDIRECT', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

    --MIXED
            ('LEVEL_2', false, true, 'navy', 180, 'MIXED','INDIRECT', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'MIXED','INDIRECT', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'MIXED','INDIRECT', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'MIXED','INDIRECT', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'MIXED','INDIRECT', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'MIXED','INDIRECT', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'MIXED','INDIRECT', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'MIXED','INDIRECT', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'MIXED','INDIRECT', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'MIXED','INDIRECT', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'MIXED','INDIRECT', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'MIXED','INDIRECT', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'MIXED','INDIRECT', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'MIXED','INDIRECT', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'MIXED','INDIRECT', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'MIXED','INDIRECT', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'MIXED','INDIRECT', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'MIXED','INDIRECT', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'MIXED','INDIRECT', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'MIXED','INDIRECT', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'MIXED','INDIRECT', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'MIXED','INDIRECT', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

--CLOSED
    -- F2F
            ('LEVEL_2', false, true, 'navy', 180, 'F2F','CLOSED', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'F2F','CLOSED', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'F2F','CLOSED', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'F2F','CLOSED', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'F2F','CLOSED', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'F2F','CLOSED', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'F2F','CLOSED', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'F2F','CLOSED', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'F2F','CLOSED', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'F2F','CLOSED', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'F2F','CLOSED', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'F2F','CLOSED', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'F2F','CLOSED', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'F2F','CLOSED', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'F2F','CLOSED', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'F2F','CLOSED', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'F2F','CLOSED', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'F2F','CLOSED', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'F2F','CLOSED', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'F2F','CLOSED', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'F2F','CLOSED', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'F2F','CLOSED', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

    -- VIRTUAL
            ('LEVEL_2', false, true, 'navy', 180, 'VIRTUAL','CLOSED', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'VIRTUAL','CLOSED', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'VIRTUAL','CLOSED', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'VIRTUAL','CLOSED', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'VIRTUAL','CLOSED', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'VIRTUAL','CLOSED', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'VIRTUAL','CLOSED', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'VIRTUAL','CLOSED', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'VIRTUAL','CLOSED', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'VIRTUAL','CLOSED', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'VIRTUAL','CLOSED', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'VIRTUAL','CLOSED', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'VIRTUAL','CLOSED', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'VIRTUAL','CLOSED', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'VIRTUAL','CLOSED', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'VIRTUAL','CLOSED', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'VIRTUAL','CLOSED', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'VIRTUAL','CLOSED', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'VIRTUAL','CLOSED', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'VIRTUAL','CLOSED', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'VIRTUAL','CLOSED', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'VIRTUAL','CLOSED', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

    --MIXED
            ('LEVEL_2', false, true, 'navy', 180, 'MIXED','CLOSED', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'MIXED','CLOSED', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'MIXED','CLOSED', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 15, 'MIXED','CLOSED', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 140, 'MIXED','CLOSED', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 20, 'MIXED','CLOSED', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 30, 'MIXED','CLOSED', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'navy', 60, 'MIXED','CLOSED', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'MIXED','CLOSED', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 90, 'MIXED','CLOSED', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', false, true, 'purple', 40, 'MIXED','CLOSED', 'Transport Level Two ANZ', 11, false, false, 'ANZ'),

            ('LEVEL_2', true, true, 'navy', 180, 'MIXED','CLOSED', 'Theory Level Two ANZ', 1, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'MIXED','CLOSED', 'Communication Level Two ANZ', 2, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'MIXED','CLOSED', 'Physical Warm Up Level Two ANZ', 3, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 15, 'MIXED','CLOSED', 'Elevated Risks Level Two ANZ', 4, true, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 140, 'MIXED','CLOSED', 'Personal Safety Modules - Assess Risk, Reduce Risk, Gates Level Two ANZ', 5, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 20, 'MIXED','CLOSED', 'Prompts and Guides Level Two ANZ', 6, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 30, 'MIXED','CLOSED', 'Seperations Level Two ANZ', 7, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'navy', 60, 'MIXED','CLOSED', 'Small Child and One Person Holds Level Two ANZ', 8, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'MIXED','CLOSED', 'Two Person Standing Holds Level Two ANZ', 9, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 90, 'MIXED','CLOSED', 'Two Person Seated Holds Level Two ANZ', 10, false, false, 'ANZ'),
            ('LEVEL_2', true, true, 'purple', 40, 'MIXED','CLOSED', 'Transport Level Two ANZ', 11, false, false, 'ANZ');