INSERT INTO module_group (name, course_level) VALUES
('Theory', 'LEVEL_1'),
('Theory', 'LEVEL_2'),
('Personal Space & Body Language', 'LEVEL_1'),
('Personal Space & Body Language', 'LEVEL_2'),
('Elevated Risks', 'LEVEL_1'),
('Elevated Risks', 'LEVEL_2'),
('Physical Warm Up', 'LEVEL_1'),
('Physical Warm Up', 'LEVEL_2'),
('Personal Safety', 'LEVEL_1'),
('Personal Safety', 'LEVEL_2'),
('Neck Disengagement', 'LEVEL_1'),
('Neck Disengagement', 'LEVEL_2'),
('Prompts Guides & Separations', 'LEVEL_1'),
('Prompts Guides & Separations', 'LEVEL_2'),
('Clothing Hair & Bite Responses', 'LEVEL_1'),
('Clothing Hair & Bite Responses', 'LEVEL_2'),
('Small Child and One Person Holds', 'LEVEL_1'),
('Small Child and One Person Holds', 'LEVEL_2'),
('Two Person Escorts and Seated Holds', 'LEVEL_2'),
('Advanced Warm Up ', 'ADVANCED'),
('Ground Recovery Techniques', 'ADVANCED'),
('Additional Ground Responses', 'ADVANCED'),
('Dead Weight Response', 'ADVANCED'),
('Everyday Objects Used As Weapons', 'ADVANCED'),
('Transport', 'ADVANCED');
