INSERT INTO module_group (name, course_level, color) VALUES
('Theory', 'LEVEL_1', 'navy'),
('Theory', 'LEVEL_2', 'navy'),
('Personal Space & Body Language', 'LEVEL_1', 'navy'),
('Personal Space & Body Language', 'LEVEL_2', 'navy'),
('Elevated Risks', 'LEVEL_1', 'navy'),
('Elevated Risks', 'LEVEL_2', 'navy'),
('Physical Warm Up', 'LEVEL_1', 'navy'),
('Physical Warm Up', 'LEVEL_2', 'navy'),
('Personal Safety', 'LEVEL_1', 'navy'),
('Personal Safety', 'LEVEL_2', 'navy'),
('Neck Disengagement', 'LEVEL_1', 'navy'),
('Neck Disengagement', 'LEVEL_2', 'navy'),
('Prompts Guides & Separations', 'LEVEL_1', 'navy'),
('Prompts Guides & Separations', 'LEVEL_2', 'navy'),
('Clothing Hair & Bite Responses', 'LEVEL_1', 'navy'),
('Clothing Hair & Bite Responses', 'LEVEL_2', 'navy'),
('Small Child and One Person Holds', 'LEVEL_1', 'navy'),
('Small Child and One Person Holds', 'LEVEL_2', 'navy'),
('Two Person Escorts and Seated Holds', 'LEVEL_2', 'purple'),
('Advanced Warm Up ', 'ADVANCED', 'fuschia'),
('Ground Recovery Techniques', 'ADVANCED', 'fuschia'),
('Additional Ground Responses', 'ADVANCED', 'fuschia'),
('Dead Weight Response', 'ADVANCED', 'fuschia'),
('Everyday Objects Used As Weapons', 'ADVANCED', 'fuschia'),
('Transport', 'ADVANCED', 'fuschia');
