UPDATE module_group
SET name = 'Advanced Warm Up'
WHERE name = 'Advanced Warm Up ';

-- Level 1 Virtual, no go1, no reaccreditation
INSERT INTO module_group_duration (module_group_id, course_delivery_type, reaccreditation, duration, go1_integration)
VALUES ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'VIRTUAL', 
        false,
        240,
        false),
        ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'VIRTUAL', 
        false,
        120,
        false);

INSERT INTO module_group_duration (module_group_id, course_delivery_type, reaccreditation, duration, go1_integration)
VALUES ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        180,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        60,
        false),

       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        90,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        30,
        false),

        ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        90,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'MIXED',
        true,
        30,
        false),

        ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        90,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        true,
        30,
        false),

       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        60,
        true),

        ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'VIRTUAL',
        false,
        60,
        true),

       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        180,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        90,
        false),
        ((SELECT id FROM module_group WHERE name = 'Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        90,
        false),

        ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        180,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        20,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        90,
        false),
        ((SELECT id FROM module_group WHERE name = 'Seated Holds' and course_level = 'LEVEL_2'),
        'MIXED',
        false,
        90,
        false),

       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        90,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        45,
        false),
        ((SELECT id FROM module_group WHERE name = 'Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        45,
        false),

        ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        90,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        15,
        false),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        45,
        false),
        ((SELECT id FROM module_group WHERE name = 'Seated Holds' and course_level = 'LEVEL_2'),
        'MIXED',
        true,
        45,
        false),

       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        true),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        60,
        true),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        90,
        true),
        ((SELECT id FROM module_group WHERE name = 'Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        90,
        true),

       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        true),
        ((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        true),
        ((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        true),
        ((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        45,
        true),
        ((SELECT id FROM module_group WHERE name = 'Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        45,
        true);

INSERT INTO module_group_duration (module_group_id, course_delivery_type, reaccreditation, duration, go1_integration)
VALUES
    ((SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'LEVEL_1'), 'MIXED', false, 90, false),
    ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'LEVEL_1'), 'MIXED', false, 60, false),
    ((SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_1'), 'MIXED', false, 15, false),
    ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_1'), 'MIXED', false, 15, false),
    ((SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1'), 'MIXED', false, 20, false),
    ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1'), 'MIXED', false, 20, false),
    ((SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_1'), 'MIXED', false, 15, false),
    ((SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'LEVEL_1'), 'MIXED', false, 15, false),
    ((SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_1'), 'MIXED', false, 15, false),
    ((SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_1'), 'MIXED', false, 15, false),
    ((SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_1'), 'MIXED', false, 15, false),
    ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1'), 'MIXED', false, 30, false);

