UPDATE module_group
SET name = 'Advanced Warm Up'
WHERE name = 'Advanced Warm Up ';

INSERT INTO module_group_duration (module_group_id, course_delivery_type, reaccreditation, duration)
VALUES ((SELECT id FROM module_group WHERE name = 'Theory' and module_level = 1),
        'F2F',
        false,
        120),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and module_level = 1),
        'F2F',
        false,
        120),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and module_level = 1),
        'F2F',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and module_level = 1),
        'F2F',
        false,
        15),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and module_level = 1),
        'F2F',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and module_level = 1),
        'F2F',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and module_level = 1),
        'F2F',
        false,
        40),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and module_level = 1),
        'F2F',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and module_level = 1),
        'F2F',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Theory' and module_level = 1),
        'F2F',
        true,
        60),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and module_level = 1),
        'F2F',
        true,
        60),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and module_level = 1),
        'F2F',
        true,
        45),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and module_level = 1),
        'F2F',
        true,
        15),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and module_level = 1),
        'F2F',
        true,
        20),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and module_level = 1),
        'F2F',
        true,
        20),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and module_level = 1),
        'F2F',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and module_level = 1),
        'F2F',
        true,
        45),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and module_level = 1),
        'F2F',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Theory' and module_level = 1),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and module_level = 1),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and module_level = 1),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and module_level = 1),
        'BLENDED',
        false,
        15),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and module_level = 1),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and module_level = 1),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and module_level = 1),
        'BLENDED',
        false,
        40),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and module_level = 1),
        'BLENDED',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and module_level = 1),
        'BLENDED',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Theory' and module_level = 2),
        'F2F',
        false,
        120),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and module_level = 2),
        'F2F',
        false,
        120),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and module_level = 2),
        'F2F',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and module_level = 2),
        'F2F',
        false,
        15),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and module_level = 2),
        'F2F',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and module_level = 2),
        'F2F',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and module_level = 2),
        'F2F',
        false,
        40),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and module_level = 2),
        'F2F',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and module_level = 2),
        'F2F',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and module_level = 2),
        'F2F',
        false,
        180),
       ((SELECT id FROM module_group WHERE name = 'Theory' and module_level = 2),
        'F2F',
        true,
        60),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and module_level = 2),
        'F2F',
        true,
        60),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and module_level = 2),
        'F2F',
        true,
        45),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and module_level = 2),
        'F2F',
        true,
        15),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and module_level = 2),
        'F2F',
        true,
        20),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and module_level = 2),
        'F2F',
        true,
        20),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and module_level = 2),
        'F2F',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and module_level = 2),
        'F2F',
        true,
        45),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and module_level = 2),
        'F2F',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and module_level = 2),
        'F2F',
        true,
        90),
       ((SELECT id FROM module_group WHERE name = 'Theory' and module_level = 2),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and module_level = 2),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and module_level = 2),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and module_level = 2),
        'BLENDED',
        false,
        15),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and module_level = 2),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and module_level = 2),
        'BLENDED',
        false,
        30),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and module_level = 2),
        'BLENDED',
        false,
        40),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and module_level = 2),
        'BLENDED',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and module_level = 2),
        'BLENDED',
        false,
        60),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and module_level = 2),
        'BLENDED',
        false,
        180),
       ((SELECT id FROM module_group WHERE name = 'Theory' and module_level = 2),
        'BLENDED',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and module_level = 2),
        'BLENDED',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and module_level = 2),
        'BLENDED',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and module_level = 2),
        'BLENDED',
        true,
        15),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and module_level = 2),
        'BLENDED',
        true,
        20),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and module_level = 2),
        'BLENDED',
        true,
        20),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and module_level = 2),
        'BLENDED',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and module_level = 2),
        'BLENDED',
        true,
        45),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and module_level = 2),
        'BLENDED',
        true,
        30),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and module_level = 2),
        'BLENDED',
        true,
        90),
       ((SELECT id FROM module_group WHERE name = 'Advanced Warm Up' and module_level = 3),
        'F2F',
        false,
        15),
       ((SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' and module_level = 3),
        'F2F',
        false,
        360),
       ((SELECT id FROM module_group WHERE name = 'Additional Ground Responses' and module_level = 3),
        'F2F',
        false,
        180),
       ((SELECT id FROM module_group WHERE name = 'Dead Weight Response' and module_level = 3),
        'F2F',
        false,
        20),
       ((SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' and module_level = 3),
        'F2F',
        false,
        360),
       ((SELECT id FROM module_group WHERE name = 'Transport' and module_level = 3),
        'F2F',
        false,
        60);
