UPDATE module_group
SET name = 'Advanced Warm Up'
WHERE name = 'Advanced Warm Up ';

INSERT INTO module_group_duration (module_group_id, course_delivery_type, reaccreditation, duration, go1_integration)
VALUES ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        120,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        120,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        40,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        45,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        45,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'F2F',
        true,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        40,
        true),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        60,
        true),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_1'),
        'F2F',
        false,
        60,
        true),
       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        120,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        120,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        40,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        180,
        false),
       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        60,
        false),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        45,
        false),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        45,
        false),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        false),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        90,
        false),
       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        40,
        true),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        60,
        true),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        60,
        true),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        false,
        180,
        true),
       ((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        15,
        true),
       ((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        20,
        true),
       ((SELECT id FROM module_group WHERE name = 'Prompts Guides & Separations' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Clothing Hair & Bite Responses' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        45,
        true),
       ((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        30,
        true),
       ((SELECT id FROM module_group WHERE name = 'Two Person Escorts and Seated Holds' and course_level = 'LEVEL_2'),
        'F2F',
        true,
        90,
        true),
       ((SELECT id FROM module_group WHERE name = 'Advanced Warm Up' and course_level = 'ADVANCED'),
        'F2F',
        false,
        15,
        false),
       ((SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' and course_level = 'ADVANCED'),
        'F2F',
        false,
        360,
        false),
       ((SELECT id FROM module_group WHERE name = 'Additional Ground Responses' and course_level = 'ADVANCED'),
        'F2F',
        false,
        180,
        false),
       ((SELECT id FROM module_group WHERE name = 'Dead Weight Response' and course_level = 'ADVANCED'),
        'F2F',
        false,
        20,
        false),
       ((SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' and course_level = 'ADVANCED'),
        'F2F',
        false,
        360,
        false),
       ((SELECT id FROM module_group WHERE name = 'Transport' and course_level = 'ADVANCED'),
        'F2F',
        false,
        60,
        false);
