UPDATE module_group
SET name = 'Response to Ground Assaults'
WHERE name = 'Additional Ground Responses';

INSERT INTO
    module (
    name,
    course_level,
    module_category,
    module_group_id
)
VALUES
('Positional Asphyxia & Hyper Flexion', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_1')),
('Pressure on Abdomen & ribcage', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_1')),
('Leaning forward', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_1')),
('Prone restraint', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_1')),
('Pulse raisers', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_1')),
('Stretches', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_1')),
('Row boat & ride bike', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_1')),
('Pass ball', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_1')),
('Sensitivity of fingers', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_1')),
('Arm responses', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Side step in', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Drop elbow', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Pump', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Conductor', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Clock', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Cross over', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Body Disengagements', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_1')),
('Steering wheel', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Fix & stabilise', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Windmill', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Snake', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Elbow Swing', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Neck Brace', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Bar & brace- behind', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Elbow guide out of headlock', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Spin out of strangle', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_1')),
('Show and go', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_1')),
('Caring C guide', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_1')),
('Turn gather guide', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_1')),
('Steering away', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_1')),
('Arm waltz', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_1')),
('Punches & kicks', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'LEVEL_1')),
('Half shield', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'LEVEL_1')),
('Turn gather guide', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'LEVEL_1')),
('Closed fist hold', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_1')),
('Tube grip', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_1')),
('Close to the neck', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_1')),
('From behind', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_1')),
('One handed grab', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_1')),
('Two handed grab', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_1')),
('Oyster', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_1')),
('Knuckle roll', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_1')),
('Knuckle slide', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_1')),
('Bite responses', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_1')),
('Eye bulge', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_1')),
('Distraction', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_1')),
('Jaw manual manipulation', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_1')),
('Moving in hold', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),
('Sitting in hold', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),
('Chairs/beanbags to hold', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),
('Change of face in seated position', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),
('Sitting to floor', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),
('Help along side', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),
('Response to dead weight', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),
('Single person double elbow + support', 'LEVEL_1', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_1')),

('Positional Asphyxia & Hyper Flexion', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_2')),
('Pressure on Abdomen & ribcage', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_2')),
('Leaning forward', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_2')),
('Prone restraint', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'LEVEL_2')),
('Pulse raisers', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_2')),
('Stretches', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_2')),
('Row boat & ride bike', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_2')),
('Pass ball', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_2')),
('Sensitivity of fingers', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'LEVEL_2')),
('Arm responses', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Side step in', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Drop elbow', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Pump', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Conductor', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Clock', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Cross over', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Body Disengagements', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'LEVEL_2')),
('Steering wheel', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Fix & stabilise', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Windmill', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Snake', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Elbow Swing', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Neck Brace', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Bar & brace- behind', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Elbow guide out of headlock', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Spin out of strangle', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'LEVEL_2')),
('Show and go', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_2')),
('Caring C guide', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_2')),
('Steering away', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_2')),
('Arm waltz', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_2')),
('Turn gather guide', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'LEVEL_2')),
('Punches & kicks', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'LEVEL_2')),
('Half shield', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'LEVEL_2')),
('Turn gather guide', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'LEVEL_2')),
('Closed fist hold', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_2')),
('Tube grip', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_2')),
('Close to the neck', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_2')),
('From behind', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'LEVEL_2')),
('One handed grab', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_2')),
('Two handed grab', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_2')),
('Oyster', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_2')),
('Knuckle roll', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_2')),
('Knuckle slide', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'LEVEL_2')),
('Bite responses', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_2')),
('Eye bulge', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_2')),
('Distraction', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_2')),
('Jaw manual manipulation', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'LEVEL_2')),
('Moving in hold', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Sitting in hold', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Chairs/beanbags to hold', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Change of face in seated position', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Sitting to floor', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Help along side', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Response to dead weight', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Single person double elbow + support', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'LEVEL_2')),
('Friendly', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'LEVEL_2')),
('Single elbow', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'LEVEL_2')),
('Figure of four', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'LEVEL_2')),
('Double elbow', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'LEVEL_2')),
('Response to spitting', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'LEVEL_2')),
('Moving in hold', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'LEVEL_2')),
('Response to dead weight', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'LEVEL_2')),
('Sitting in hold / bean bag option', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),
('Moving to seated position', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),
('Foot wedge', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),
('Responses to kicking', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),
('Change of face in seats', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),
('Alternative change of face in seated', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),
('Small child escorts', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),
('Response to dead weight', 'LEVEL_2', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'LEVEL_2')),

('Stretch kneeling to the ground', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED')),
('The triangular dance', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED')),
('Attack 5 step aside', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED')),
('Kneeling to front ground recovery', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Ground position support arms', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help with legs', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help replacing person at legs', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Additional feet support', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help replacing person at the head (leg side)', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help replacing person at head (head side)', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Hip chair', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Back ground recovery', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help with legs', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help with supporting arm', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Shield hold / escort', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Cradle sitting shield', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Ground shield', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Ground shield into front ground recovery', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help with legs in ground shield', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Help with ground shield into front ground recovery', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED')),
('Ground assaults', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED')),
('Knee guide', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED')),
('Shoulder drop', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED')),
('Raise extend', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED')),
('Ground fights', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED')),
('Two-person response to ground fights', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED')),
('Single person emergency response to ground fights', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED')),
('Dead weight off the ground', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Dead Weight Response' AND course_level = 'ADVANCED')),
('Attacks with objects', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Attacks with sharp, pointed and edged objects', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Pool cues and sticks', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Pool cue bar strangle from behind', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Pool cue bar strangle from front', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Missiles', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Chairs', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Fix and stabilise', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Elbow guide', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Everyday Objects Used As Weapons' AND course_level = 'ADVANCED')),
('Risks associated with transport', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Driver', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Vehicle design', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Objects used as weapons', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Tow rope, Jack, wheel brace, head rest', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Seating arrangements', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Positive handling plans', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Before boarding', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Responding to dangerous behaviour', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Bracing against vehicle', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Securing a seatbelt', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED')),
('Dead weight off the ground', 'ADVANCED', 'THEORY', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'));
