INSERT into module_group (name, mandatory, course_level, color) VALUES 
('Theory', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Personal Space & Body Language', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Elevated Risks', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Physical Warm Up', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Personal Safety', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Neck Disengagement', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Prompts Guides', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Separations', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Clothing Responses', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Hair Responses', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Bite Responses', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Small Child and One Person Holds', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Two Person Escorts', true, 'INTERMEDIATE_TRAINER', 'navy'),
('Seated Holds', true, 'INTERMEDIATE_TRAINER', 'navy');

INSERT into module_group_duration (module_group_id, course_delivery_type, reaccreditation, go1_integration, duration) VALUES
((SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 180),
((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 60),
((SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Prompts Guides' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 60),
((SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 90),
((SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', false, false, 90),

((SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 90),
((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 60),
((SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 15),
((SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 15),
((SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 20),
((SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 20),
((SELECT id FROM module_group WHERE name = 'Prompts Guides' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 15),
((SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 15),
((SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 15),
((SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 15),
((SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 15),
((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 30),
((SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 45),
((SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'F2F', true, false, 45);

INSERT INTO module (name, module_group_id, module_category, course_level) VALUES
('Values excercise', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Legal framework', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Policies Practices & procedure', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Understanding emotions & behaviour', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Six stages of crisis', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Conflict spiral', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Fizzy pop challenge', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Behaviours that challenge', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('De-escalation scenario', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Handling plans', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Scripts', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Post listening & learning', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Quiz', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Circles of danger', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Posturing and body language', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Experiencing feeling', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Calm stance', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Calming scripts', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Positional Asphixia & Hyper Flexion', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Pressure on Abdomen & ribcage', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Leaning forward', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Prone restraint', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Pulse raisers', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Stretches', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Row boat & ride bike', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Pass ball', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Sensitivity of fingers', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Arm responses', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Side step in', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Drop elbow', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Pump', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Conductor', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Clock', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Cross over', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Body Disengagements', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Steering wheel', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Fix & stabilise', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Windmill', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Snake', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Elbow Swing', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Neck Brace', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Bar & brace - behind', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Elbow guide out of headlock', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Spin out of strangle', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Show and go', (SELECT id FROM module_group WHERE name = 'Prompts Guides' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Caring C guide', (SELECT id FROM module_group WHERE name = 'Prompts Guides' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Turn gather guide', (SELECT id FROM module_group WHERE name = 'Prompts Guides' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Steering away', (SELECT id FROM module_group WHERE name = 'Prompts Guides' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Arm waltz', (SELECT id FROM module_group WHERE name = 'Prompts Guides' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Punches & kicks', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Half shield', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Turn gather guide', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Closed fist hold', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Tube grip', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Close to the neck', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('From behind', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('One handed grab', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Two handed grab', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Oyster', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Knuckle roll', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Knuckle slide', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Bite responses', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Eye bulge', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Distraction', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Jaw manual manipulation', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Moving in hold', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Sitting in hold', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Chairs/beanbags to hold', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Change of face in seated position', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Sitting to floor', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Help along side', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Response to dead weight', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Single person double elbow + support', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Friendly', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Single elbow', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Figure of four', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Double elbow', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Response to spitting', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Moving in hold', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Response to dead weight', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),

('Sitting in hold / bean bag option', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Moving to seated position', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Foot wedge', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Responses to kicking', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Change of face in seats', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Alternative change of face in seated', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Small child escorts', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER'),
('Response to dead weight', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'INTERMEDIATE_TRAINER'), 'THEORY', 'INTERMEDIATE_TRAINER');