INSERT into module_group (name, mandatory, course_level, color) VALUES
('Theory', true, 'ADVANCED_TRAINER', 'fuschia'),
('Personal Space & Body Language', true, 'ADVANCED_TRAINER', 'fuschia'),
('Elevated Risks', true, 'ADVANCED_TRAINER', 'fuschia'),
('Physical Warm Up', true, 'ADVANCED_TRAINER', 'fuschia'),
('Personal Safety', true, 'ADVANCED_TRAINER', 'fuschia'),
('Neck Disengagement', true, 'ADVANCED_TRAINER', 'fuschia'),
('Prompts and Guides', true, 'ADVANCED_TRAINER', 'fuschia'),
('Separations', true, 'ADVANCED_TRAINER', 'fuschia'),
('Clothing Responses', true, 'ADVANCED_TRAINER', 'fuschia'),
('Hair Responses', true, 'ADVANCED_TRAINER', 'fuschia'),
('Bite Responses', true, 'ADVANCED_TRAINER', 'fuschia'),
('Small Child and One Person Holds', true, 'ADVANCED_TRAINER', 'fuschia'),
('Two Person Escorts', true, 'ADVANCED_TRAINER', 'fuschia'),
('Seated Holds', true, 'ADVANCED_TRAINER', 'fuschia'),

('Advanced Warm Up', true, 'ADVANCED_TRAINER', 'fuschia'),
('Ground Recovery Techniques', true, 'ADVANCED_TRAINER', 'fuschia'),
('Response to Ground Assaults', true, 'ADVANCED_TRAINER', 'fuschia'),
('Dead Weight Response', true, 'ADVANCED_TRAINER', 'fuschia'),
('Everyday Objects', true, 'ADVANCED_TRAINER', 'fuschia'),
('Legal & Health', true, 'ADVANCED_TRAINER', 'fuschia'),
('Transport', true, 'ADVANCED_TRAINER', 'fuschia');

INSERT into module_group_duration (module_group_id, course_delivery_type, reaccreditation, go1_integration, duration) VALUES
((SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 15),
((SELECT id FROM module_group WHERE name = 'Legal & Health' AND course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 120),
((SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Dead Weight Response' AND course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 15),
((SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 120),
((SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 40),

((SELECT id FROM module_group WHERE name = 'Theory' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Elevated Risks' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Physical Warm Up' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 15),
((SELECT id FROM module_group WHERE name = 'Personal Safety' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Neck Disengagement' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Prompts and Guides' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Separations' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Clothing Responses' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Hair Responses' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Bite Responses' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 60),
((SELECT id FROM module_group WHERE name = 'Two Person Escorts' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 90),
((SELECT id FROM module_group WHERE name = 'Seated Holds' and course_level = 'ADVANCED_TRAINER'), 'F2F', false, false, 90);

INSERT INTO module (name, module_group_id, module_category, course_level) VALUES
('Stretch kneeling to the ground', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('The triangular dance', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Attack 5 step aside', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),

('Kneeling to front ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Ground position support arms', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help with legs', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help replacing person at legs', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Additional feet support', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help replacing person at the head (leg side)', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help replacing person at head (head side)', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Hip chair', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Back ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help with legs', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help with supporting arm', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Shield hold / escort', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Cradle sitting shield', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Ground shield', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Ground shield into front ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help with legs in ground shield', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Help with ground shield into front ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),

('Ground assaults', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Knee guide', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Shoulder drop', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Raise extend', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Ground fights', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Two-person response to ground fights', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Single person emergency response to ground fights', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),

('Dead weight off the ground', (SELECT id FROM module_group WHERE name = 'Dead Weight Response' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),

('Attacks with objects', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle one', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle two', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle three', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle four', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle five', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Attacks with sharp, pointed and edged objects', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle one', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle two', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle four', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle five', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Pool cues and sticks', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle two', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle four', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle five', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Pool cue bar strangle from behind', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Pool cue bar strangle from front', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Missiles', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Chairs', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle 2', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Angle 5', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Fix and stabilise', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Elbow guide', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),

('Risks associated with transport', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Driver', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Vehicle design', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Objects used as weapons', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Tow rope, Jack, wheel brace, head rest', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Seating arrangements', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Positive handling plans', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Before boarding', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Responding to dangerous behaviour', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Bracing against vehicle', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Securing a seatbelt', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER'),
('Dead weight off the ground', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED_TRAINER'), 'THEORY', 'ADVANCED_TRAINER');

INSERT INTO module (name, course_level, module_category, module_group_id)
VALUES 
('Values Exercise', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Legal Framework', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Policies Practices & Procedure', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Understanding Emotions & Behaviour', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Six Stages Of Crisis', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Conflict Spiral', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Fizzy Pop Challenge', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Behaviours That Challenge', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('De-escalation Scenario', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Handling Plans', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Scripts', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Post Listening & Learning', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Quiz', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Theory' AND course_level = 'ADVANCED_TRAINER')),
('Circles Of Danger', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'ADVANCED_TRAINER')),
('Posturing And Body Language', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'ADVANCED_TRAINER')),
('Experiencing Feeling', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'ADVANCED_TRAINER')),
('Calm Stance', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'ADVANCED_TRAINER')),
('Calming Scripts', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Space & Body Language' AND course_level = 'ADVANCED_TRAINER'));

INSERT INTO
    module (
    name,
    course_level,
    module_category,
    module_group_id
)
VALUES
('Positional Asphyxia & Hyper Flexion', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'ADVANCED_TRAINER')),
('Pressure on Abdomen & ribcage', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'ADVANCED_TRAINER')),
('Leaning forward', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'ADVANCED_TRAINER')),
('Prone restraint', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Elevated Risks' AND course_level = 'ADVANCED_TRAINER')),
('Pulse raisers', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'ADVANCED_TRAINER')),
('Stretches', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'ADVANCED_TRAINER')),
('Row boat & ride bike', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'ADVANCED_TRAINER')),
('Pass ball', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'ADVANCED_TRAINER')),
('Sensitivity of fingers', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Physical Warm Up' AND course_level = 'ADVANCED_TRAINER')),
('Arm responses', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Side step in', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Drop elbow', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Pump', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Conductor', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Clock', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Cross over', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Body Disengagements', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Personal Safety' AND course_level = 'ADVANCED_TRAINER')),
('Steering wheel', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Fix & stabilise', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Windmill', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Snake', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Elbow Swing', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Neck Brace', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Bar & brace- behind', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Elbow guide out of headlock', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Spin out of strangle', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Neck Disengagement' AND course_level = 'ADVANCED_TRAINER')),
('Show and go', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'ADVANCED_TRAINER')),
('Caring C guide', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'ADVANCED_TRAINER')),
('Steering away', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'ADVANCED_TRAINER')),
('Arm waltz', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'ADVANCED_TRAINER')),
('Turn gather guide', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Prompts and Guides' AND course_level = 'ADVANCED_TRAINER')),
('Punches & kicks', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'ADVANCED_TRAINER')),
('Half shield', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'ADVANCED_TRAINER')),
('Turn gather guide', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Separations' AND course_level = 'ADVANCED_TRAINER')),
('Closed fist hold', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'ADVANCED_TRAINER')),
('Tube grip', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'ADVANCED_TRAINER')),
('Close to the neck', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'ADVANCED_TRAINER')),
('From behind', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Clothing Responses' AND course_level = 'ADVANCED_TRAINER')),
('One handed grab', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'ADVANCED_TRAINER')),
('Two handed grab', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'ADVANCED_TRAINER')),
('Oyster', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'ADVANCED_TRAINER')),
('Knuckle roll', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'ADVANCED_TRAINER')),
('Knuckle slide', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Hair Responses' AND course_level = 'ADVANCED_TRAINER')),
('Bite responses', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'ADVANCED_TRAINER')),
('Eye bulge', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'ADVANCED_TRAINER')),
('Distraction', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'ADVANCED_TRAINER')),
('Jaw manual manipulation', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Bite Responses' AND course_level = 'ADVANCED_TRAINER')),
('Moving in hold', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Sitting in hold', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Chairs/beanbags to hold', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Change of face in seated position', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Sitting to floor', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Help along side', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Response to dead weight', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Single person double elbow + support', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Small Child and One Person Holds' AND course_level = 'ADVANCED_TRAINER')),
('Friendly', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'ADVANCED_TRAINER')),
('Single elbow', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'ADVANCED_TRAINER')),
('Figure of four', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'ADVANCED_TRAINER')),
('Double elbow', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'ADVANCED_TRAINER')),
('Response to spitting', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'ADVANCED_TRAINER')),
('Moving in hold', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'ADVANCED_TRAINER')),
('Response to dead weight', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Two Person Escorts' AND course_level = 'ADVANCED_TRAINER')),
('Sitting in hold / bean bag option', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER')),
('Moving to seated position', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER')),
('Foot wedge', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER')),
('Responses to kicking', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER')),
('Change of face in seats', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER')),
('Alternative change of face in seated', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER')),
('Small child escorts', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER')),
('Response to dead weight', 'ADVANCED_TRAINER', 'THEORY', (SELECT id FROM module_group WHERE name = 'Seated Holds' AND course_level = 'ADVANCED_TRAINER'));
