INSERT into module_group (name, mandatory, course_level, color) VALUES 
('Advanced Warm Up', true, 'ADVANCED', 'fuschia'),
('Ground Recovery Techniques', false, 'ADVANCED', 'fuschia'),
('Response to Ground Assaults', false, 'ADVANCED', 'fuschia'),
('Dead Weight Response', true, 'ADVANCED', 'fuschia'),
('Everyday Objects', false, 'ADVANCED', 'fuschia'),
('Legal & Health', true, 'ADVANCED', 'fuschia'),
('Transport', false, 'ADVANCED', 'fuschia');

INSERT into module_group_duration (module_group_id, course_delivery_type, reaccreditation, go1_integration, duration) VALUES
((SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED'), 'F2F', false, false, 15),
((SELECT id FROM module_group WHERE name = 'Legal & Health' AND course_level = 'ADVANCED'), 'F2F', false, false, 20),
((SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'F2F', false, false, 120),
((SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'F2F', false, false, 30),
((SELECT id FROM module_group WHERE name = 'Dead Weight Response' AND course_level = 'ADVANCED'), 'F2F', false, false, 15),
((SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'F2F', false, false, 120),
((SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'F2F', false, false, 40);

INSERT INTO module (name, module_group_id, module_category, course_level) VALUES
('Stretch kneeling to the ground', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('The triangular dance', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Attack 5 step aside', (SELECT id FROM module_group WHERE name = 'Advanced Warm Up' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),

('Kneeling to front ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Ground position support arms', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help with legs', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help replacing person at legs', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Additional feet support', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help replacing person at the head (leg side)', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help replacing person at head (head side)', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Hip chair', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Back ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help with legs', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help with supporting arm', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Shield hold / escort', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Cradle sitting shield', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Ground shield', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Ground shield into front ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help with legs in ground shield', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Help with ground shield into front ground recovery', (SELECT id FROM module_group WHERE name = 'Ground Recovery Techniques' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),

('Ground assaults', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Knee guide', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Shoulder drop', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Raise extend', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Ground fights', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Two-person response to ground fights', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Single person emergency response to ground fights', (SELECT id FROM module_group WHERE name = 'Response to Ground Assaults' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),

('Dead weight off the ground', (SELECT id FROM module_group WHERE name = 'Dead Weight Response' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),

('Attacks with objects', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle one', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle two', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle three', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle four', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle five', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Attacks with sharp, pointed and edged objects', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle one', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle two', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle four', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle five', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Pool cues and sticks', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle two', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle four', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle five', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Pool cue bar strangle from behind', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Pool cue bar strangle from front', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Missiles', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Chairs', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle 2', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Angle 5', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Fix and stabilise', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Elbow guide', (SELECT id FROM module_group WHERE name = 'Everyday Objects' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),

('Legal & Health', (SELECT id FROM module_group WHERE name = 'Legal & Health' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),

('Risks associated with transport', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Driver', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Vehicle design', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Objects used as weapons', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Tow rope, Jack, wheel brace, head rest', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Seating arrangements', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Positive handling plans', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Before boarding', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Responding to dangerous behaviour', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Bracing against vehicle', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Securing a seatbelt', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED'),
('Dead weight off the ground', (SELECT id FROM module_group WHERE name = 'Transport' AND course_level = 'ADVANCED'), 'THEORY', 'ADVANCED');