/// <reference types="vite/client" />
interface ImportMetaEnv {
  VITE_AWS_REGION: string
  VITE_COGNITO_USER_POOL_ID: string
  VITE_HASURA_GRAPHQL_API: string
  VITE_GMAPS_KEY: string
  VITE_BASE_WORDPRESS_URL: string
  VITE_BASE_WORDPRESS_API_URL: string
  VITE_HEALTH_AND_SAFETY_CONTENT_PATH: string
  VITE_STRIPE_KEY: string
  VITE_TT_INFO_PHONE: string
  VITE_TT_INFO_EMAIL_ADDRESS: string
  VITE_TT_TRAINING_EMAIL_ADDRESS: string
  VITE_SENTRY_DSN: string
  VITE_SENTRY_TRACING_SAMPLE_RATE: string
  VITE_SENTRY_ENVIRONMENT: string
  VITE_APP_VERSION: string
  VITE_REQUEST_QUOTE_URL: string
  VITE_MANAGE_ACCOUNT_URL: string
  VITE_UNSUBSCRIBE_URL: string
  VITE_GTM_ID: string
  VITE_RECAPTCHA_KEY: string
  VITE_WELCOME_PAGE_URL: string
}
