import { endOfDay, startOfDay } from 'date-fns'
import { useQuery } from 'urql'

import {
  CourseType,
  SearchTrainersQuery,
  SearchTrainersQueryVariables,
  CourseLevel,
} from '@app/generated/graphql'

import { Props, SEARCH_TRAINERS } from './helpers'

export const useQueryTrainers = ({
  trainerType,
  courseLevel,
  courseType,
  bildStrategies,
  schedule: { start, end },
  query,
  useAOL,
}: Props) => {
  const courseStart = start ? startOfDay(new Date(start)) : undefined
  const courseEnd = end ? endOfDay(new Date(end)) : undefined

  return useQuery<SearchTrainersQuery, SearchTrainersQueryVariables>({
    query: SEARCH_TRAINERS,
    variables: {
      input: {
        query,
        trainerType,
        courseLevel: courseLevel as CourseLevel,
        courseStart,
        courseEnd,
        courseType: courseType as unknown as CourseType, // The underlying action depends on an aditional CourseType type generated by graphql
        bildStrategies,
        useAOL,
      },
    },
    pause: !query,
  })
}
