name: CD-PROD

on:
  workflow_dispatch:

jobs:
  prod-cd:
    name: PROD
    uses: ./.github/workflows/pipeline.yml
    secrets:
      cognito_user_pool_id: ${{ secrets.COGNITO_POOL_ID_PROD }}
      cognito_user_pool_client_id: ${{ secrets.COGNITO_CLIENT_ID_PROD }}
      hasura_endpoint: ${{ secrets.HASURA_ENDPOINT_PROD }}
      s3_bucket: ${{ secrets.S3_BUCKET_PROD }}
      service_role_arn: ${{ secrets.IAM_SERVICE_PROD }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      hasura_admin_pass: ${{ secrets.HASURA_ADMIN_PASS_PROD }}