name: CD-PROD

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read  

jobs:
  prod-cd:
    name: PROD
    uses: ./.github/workflows/pipeline.yml
    secrets:
      cognito_user_pool_id: ${{ secrets.COGNITO_POOL_ID_PROD }}
      cognito_user_pool_client_id: ${{ secrets.COGNITO_CLIENT_ID_PROD }}
      hasura_endpoint: ${{ secrets.HASURA_ENDPOINT_PROD }}
      wp_host: ${{ secrets.WP_HOST_PROD }}
      s3_bucket: ${{ secrets.S3_BUCKET_PROD }}
      service_role_arn: ${{ secrets.IAM_SERVICE_PROD }}
      hasura_admin_pass: ${{ secrets.HASURA_ADMIN_PASS_PROD }}
      gmaps_key: ${{ secrets.GMAPS_KEY }}
      stripe_key: ${{ secrets.STRIPE_KEY }}
