name: RELEASE PROD VERSION

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-release:
    if: startsWith(github.head_ref, 'changeset-release/')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
