name: CD-STG

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  stg-cd:
    name: STG
    uses: ./.github/workflows/pipeline.yml
    with:
      mode: 'staging'
    secrets:
      cognito_user_pool_id: ${{ secrets.COGNITO_POOL_ID_STG }}
      cognito_user_pool_client_id: ${{ secrets.COGNITO_CLIENT_ID_STG }}
      hasura_endpoint: ${{ secrets.HASURA_ENDPOINT_STG }}
      wp_host: ${{ secrets.WP_HOST_STG }}
      s3_bucket: ${{ secrets.S3_BUCKET_STG }}
      service_role_arn: ${{ secrets.IAM_SERVICE_STG }}
      hasura_admin_pass: ${{ secrets.HASURA_ADMIN_PASS_STG }}
      gmaps_key: ${{ secrets.GMAPS_KEY }}
      recaptcha_key: ${{ secrets.RECAPTCHA_KEY }}
      stripe_key: ${{ secrets.STRIPE_KEY_STG }}
      request_quote_url: ${{ secrets.REQUEST_QUOTE_URL }}
