name: CD-STG

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag you want to deploy, leave empty for latest'
        required: false
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  stg-cd:
    name: Deploy
    uses: ./.github/workflows/pipeline.yml
    with:
      mode: 'staging'
      checkout_ref:  ${{ inputs.tag && format('refs/tags/{0}', inputs.tag) || 'refs/heads/main' }}
    secrets:
      cognito_user_pool_id: ${{ secrets.COGNITO_POOL_ID_STG }}
      cognito_user_pool_client_id: ${{ secrets.COGNITO_CLIENT_ID_STG }}
      hasura_endpoint: ${{ secrets.HASURA_ENDPOINT_STG }}
      wp_host: ${{ secrets.WP_HOST_STG }}
      s3_bucket: ${{ secrets.S3_BUCKET_STG }}
      service_role_arn: ${{ secrets.IAM_SERVICE_STG }}
      hasura_admin_pass: ${{ secrets.HASURA_ADMIN_PASS_STG }}
      gmaps_key: ${{ secrets.GMAPS_KEY }}
      recaptcha_key: ${{ secrets.RECAPTCHA_KEY }}
      stripe_key: ${{ secrets.STRIPE_KEY_STG }}
      request_quote_url: ${{ secrets.REQUEST_QUOTE_URL }}
