name: CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: CD
    runs-on: ubuntu-latest
    env:
      CD: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm t

      - name: Build web
        run: npm run build

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ ${{ secrets.S3_BUCKET }} --delete