name: CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: CD
    runs-on: ubuntu-latest
    env:
      CD: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm t

      - name: Build web
        run: export $(cat .env.development) && npm run build

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ ${{ secrets.S3_BUCKET }} --delete

  hasura_migrations:
    name: Hasura migrations
    runs-on: ubuntu-latest

    env:
      SECRET: ${{ secrets.HASURA_ADMIN_PASS }}
      ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Install Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.1.1 bash

      - name: Apply Hasura migrations
        working-directory: ./hasura
        run: |
          echo Hasura Metadata Apply
          hasura metadata apply --admin-secret $SECRET --endpoint $ENDPOINT
          echo Hasura Migrate Apply
          hasura migrate apply --all-databases --admin-secret $SECRET --endpoint $ENDPOINT
          echo Hasura Metadata Reload
          hasura metadata reload --admin-secret $SECRET --endpoint $ENDPOINT
