name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm t

      - name: Build web
        run: npm run build
