name: CI/CD-DEV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - run: echo 'NODE_OPTIONS="--max-old-space-size=4096"' >> $GITHUB_ENV

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm pkg delete scripts.prepare && npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - run: echo 'NODE_OPTIONS="--max-old-space-size=4096"' >> $GITHUB_ENV

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm pkg delete scripts.prepare && npm ci

      - name: Test
        run: npm run test  -- --maxWorkers=2 --shard=${{ matrix.shard }}/${{ strategy.job-total }} --changedSince=${{ github.event.pull_request.base.sha }}

  dev-cd:
    name: DEV
    needs: [lint-and-typecheck, test]
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'
    uses: ./.github/workflows/pipeline.yml
    with:
      mode: 'development'
    secrets:
      service_role_arn: ${{ secrets.IAM_SERVICE_DEV }}
      hasura_admin_pass: ${{ secrets.HASURA_ADMIN_PASS_DEV }}
      cognito_user_pool_id: ${{ secrets.COGNITO_POOL_ID_DEV }}
      cognito_user_pool_client_id: ${{ secrets.COGNITO_CLIENT_ID_DEV }}
      hasura_endpoint: ${{ secrets.HASURA_ENDPOINT_DEV }}
      wp_host: ${{ secrets.WP_HOST_DEV }}
      s3_bucket: ${{ secrets.S3_BUCKET_DEV }}
      gmaps_key: ${{ secrets.GMAPS_KEY }}
      stripe_key: ${{ secrets.STRIPE_KEY_DEV }}
      request_quote_url: ${{ secrets.REQUEST_QUOTE_URL }}
