name: CI/CD-DEV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '16.3.0'
          cache: 'npm'

      - run: echo 'NODE_OPTIONS="--max-old-space-size=4096"' >> $GITHUB_ENV

      - name: Install dependencies
        run: npm set-script prepare "" && npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test  -- --maxWorkers=2 --changedSince=${{ github.event.pull_request.base.sha }}

      - name: Build web
        run: npm run build -- --mode development

  dev-cd:
    name: DEV
    needs: build
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'
    uses: ./.github/workflows/pipeline.yml
    with:
      mode: 'development'
    secrets:
      service_role_arn: ${{ secrets.IAM_SERVICE_DEV }}
      hasura_admin_pass: ${{ secrets.HASURA_ADMIN_PASS_DEV }}
      cognito_user_pool_id: ${{ secrets.COGNITO_POOL_ID_DEV }}
      cognito_user_pool_client_id: ${{ secrets.COGNITO_CLIENT_ID_DEV }}
      hasura_endpoint: ${{ secrets.HASURA_ENDPOINT_DEV }}
      wp_host: ${{ secrets.WP_HOST_DEV }}
      s3_bucket: ${{ secrets.S3_BUCKET_DEV }}
      gmaps_key: ${{ secrets.GMAPS_KEY }}
      stripe_key: ${{ secrets.STRIPE_KEY }}
