name: Request Copilot Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  request-copilot-review:
    if: ${{ ! startsWith(github.head_ref, 'changeset-release/') && github.actor != 'dependabot[bot]' && ! endsWith(github.actor, '[bot]') }}
    name: Request Copilot Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review from Copilot
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers: ['copilot']
              });
              console.log('Successfully requested review from @copilot');
            } catch (error) {
              console.log('Failed to request review from @copilot:', error.message);
              // Don't fail the workflow if the API call fails
            }