name: ICM curriculum sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env you want to sync curriculums on'
        required: false
        type: choice
        options:
          - STG
          - PROD
          - DEV
env:
  DEFAULT_ENV: 'DEV'
jobs:
  curriculum-sync:
    runs-on: ubuntu-latest
    name: Curriculum Sync
    steps:
      - name: Log selected Environment
        run: echo Selected value is ---- ${{github.event.inputs.environment}}
      - name: Set hasura URL variable
        run: echo "HASURA_URL=${{ secrets[format('HASURA_ENDPOINT_{0}', github.event.inputs.environment || env.DEFAULT_ENV)] }}" >> $GITHUB_ENV
      - name: Set Hasura secret
        run: echo "HASURA_SECRET=${{ secrets[format('HASURA_ADMIN_PASS_{0}', github.event.inputs.environment || env.DEFAULT_ENV)] }}" >> $GITHUB_ENV
      - name: Sync request
        run: npx ts-node ./scripts/sync-curriculums.ts
