name: OWASP ZAP Scan

on:
  workflow_call:
    inputs:
      full:
        type: boolean
        required: true
      target_url:
        type: string
        required: true
      artifact_name:
        type: string
        required: true

jobs:
  zap-scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Sanitize Artifact Name
        id: sanitize
        run: |
          echo "SANITIZED_ARTIFACT=${{ inputs.artifact_name }}" | sed 's|https://||g; s|/|_|g' >> $GITHUB_ENV

      - name: Run ZAP Baseline Scan
        if: ${{ inputs.full == false }}
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ inputs.target_url }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: ${{ env.SANITIZED_ARTIFACT }}
          cmd_options: -j
          artifact_name: zap-scan-${{ env.SANITIZED_ARTIFACT }}

      - name: Run ZAP Full Scan
        if: ${{ inputs.full }}
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ inputs.target_url }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: ${{ env.SANITIZED_ARTIFACT }}
          cmd_options: -j
          artifact_name: zap-scan-${{ env.SANITIZED_ARTIFACT }}
