name: Pipeline

on:
  workflow_call:
    inputs:
      mode:
        type: string
        required: false
        default: 'production'
      version:
        type: string
        required: false
        default: ${{ github.sha }}
    secrets:
      cognito_user_pool_id:
        required: true
      cognito_user_pool_client_id:
        required: true
      hasura_endpoint:
        required: true
      s3_bucket:
        required: true
      service_role_arn:
        required: true
      hasura_admin_pass:
        required: true
      wp_host:
        required: true
      gmaps_key:
        required: true
      stripe_key:
        required: true

jobs:
  build-deploy:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.service_role_arn }}
          role-duration-seconds: 1200

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          cache: 'npm'

      - run: echo 'NODE_OPTIONS="--max-old-space-size=4096"' >> $GITHUB_ENV

      - name: Install dependencies
        run: npm pkg delete scripts.prepare && npm ci

      - name: Build web
        run: npm run build -- --mode ${{inputs.mode}}
        env:
          VITE_AWS_REGION: eu-west-2
          VITE_COGNITO_USER_POOL_ID: ${{ secrets.cognito_user_pool_id }}
          VITE_COGNITO_USER_POOL_CLIENT_ID: ${{ secrets.cognito_user_pool_client_id }}
          VITE_HASURA_GRAPHQL_API: '${{ secrets.hasura_endpoint }}/v1/graphql'
          VITE_BASE_WORDPRESS_URL: '${{ secrets.wp_host }}/wp-json/wp/v2'
          VITE_GMAPS_KEY: ${{ secrets.gmaps_key }}
          VITE_STRIPE_KEY: ${{ secrets.stripe_key }}
          VITE_APP_VERSION: ${{ inputs.version }}

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ ${{ secrets.s3_bucket }} --delete

  hasura_migrations:
    name: Hasura migrations
    needs: build-deploy
    runs-on: ubuntu-latest

    env:
      SECRET: ${{ secrets.hasura_admin_pass }}
      ENDPOINT: ${{ secrets.hasura_endpoint }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.6.1 bash

      - name: Apply Hasura migrations
        working-directory: ./hasura
        run: |
          echo Hasura Metadata Apply
          hasura metadata apply --admin-secret $SECRET --endpoint $ENDPOINT
          echo Hasura Migrate Apply
          hasura migrate apply --all-databases --admin-secret $SECRET --endpoint $ENDPOINT
          echo Hasura Metadata Reload
          hasura metadata reload --admin-secret $SECRET --endpoint $ENDPOINT
