name: Update course price

on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'DEV'
        description: 'Environment - "DEV/STG/PROD"'
        required: true
        type: choice
        options:
          - DEV
          - STG
          - PROD

permissions:
  id-token: write
  contents: read

env:
  DEFAULT_ENV: 'DEV'
jobs:
  data:
    name: Update course price on ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Set endpoint variable
        run: echo "ENDPOINT=${{ secrets[format('HASURA_ENDPOINT_{0}', github.event.inputs.environment || env.DEFAULT_ENV)] }}" >> $GITHUB_ENV

      - name: Set Hasura secret
        run: echo "SECRET=${{ secrets[format('HASURA_ADMIN_PASS_{0}', github.event.inputs.environment || env.DEFAULT_ENV)] }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm pkg delete scripts.prepare && pnpm i

      - name: Update course price
        run: npx ts-node ./scripts/update-course-price.ts
