name: XERO-HUB-INVOICE-SYNC

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env you want to sync invoices on'
        required: false
        type: choice
        options:
          - STG
          - PROD
          - DEV
  # schedule:
  ## Not decided if we want it periodically yet
  #   - cron: '0 0 * * *' ## run daily at 00:00

jobs:
  invoice-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Log selected Environment
        run: echo Selected value is ---- ${{github.event.inputs.environment}}
      - name: Sync request
        env:
          action_url: ${{ !github.event.inputs.environment && secrets.HASURA_ENDPOINT_DEV || join(secrets[format('HASURA_ENDPOINT_{0}', github.event.inputs.environment)])}}
          HASURA_ADMIN_SECRET: ${{ !github.event.inputs.environment && secrets.HASURA_ADMIN_PASS_DEV || secrets[format('HASURA_ADMIN_PASS_{0}', github.event.inputs.environment)] }}
        id: syncRequest
        run: |
          response=$(curl -X POST \
          -H "Content-Type: application/json" \
          -H "x-hasura-admin-secret: $HASURA_ADMIN_SECRET" \
          -d '{
            "query": "query { xeroSync { message } }"
          }' \
          $action_url)
          echo "$response"
