name: XERO-ARLO-INVOICE-SYNC

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Tag you want to deploy, leave empty for latest'
        required: false
        type: choice
        options:
          - STG
          - PROD
          - DEV
  # schedule:
  ## Not decided if we want it periodically yet
  #   - cron: '0 0 * * *' ## run daily at 00:00

jobs:
  invoice-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync request
        run: curl -X POST ${{ !inputs.environment && format('{0}/xero/invoices/sync', secrets.HASURA_ENDPOINT_DEV) || secrets[format('HASURA_ENDPOINT_{0}/xero/invoices/sync', inputs.environment)]}}
      - name: Log Response
        run: echo ${{ steps.xeroArloInvoiceSync.outputs.response }}
