name: XERO-ARLO-INVOICE-SYNC

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Tag you want to deploy, leave empty for latest'
        required: false
        type: choice
        options:
          - STG
          - PROD
          - DEV
  # schedule:
  ## Not decided if we want it periodically yet
  #   - cron: '0 0 * * *' ## run daily at 00:00

env:
  ### DEFAULT TO DEV
  action_url: ${{ !inputs.environment && secrets[format('HASURA_ENDPOINT_DEV/{0}', 'xero/invoice/sync')] || secrets[format('HASURA_ENDPOINT_{0}/{1}', inputs.environment, 'xero/invoice/sync')]}}

jobs:
  invoice-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Log action url
        run: echo Action URL is ${{env.action_url}}
      - name: Trigger hub-api request
        id: xeroArloInvoiceSync
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.action_url }}
          method: POST
      - name: Log Response
        run: echo ${{ steps.xeroArloInvoiceSync.outputs.response }}
